- API.Tests/MapperTests/PostProjectsRequestMapperTests.cs
- TRAMS-API/API.xml
- TRAMS-API/Mapping/PostProjectsRequestMapper.cs
Intervention Reasons: D365 POST Model properties must be null (not empty string) if the upstream reason arrays are null or empty  
Update tests to assert downstream reason string properties are null
> Intervention Reasons Bug Fix

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Views/Transfers/OutgoingTrustDetails.cshtml
- Frontend/Views/Transfers/OutgoingTrustDetails.cshtml.cs
- Frontend/Views/Transfers/TrustSearch.cshtml
As part of the ongoing rewrite, this recreates the confirmation page for the outgoing trust.
- Add links to the outgoing trust page from the trust search results
- Add confirmation details page for outgoing trust
> Add outgoing trust details confirmation page

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Startup.cs
- Frontend/Views/Transfers/IncomingTrustIdentified.cshtml
- Frontend/Views/Transfers/OutgoingTrustAcademies.cshtml
- Frontend/Views/Transfers/OutgoingTrustAcademies.cshtml.cs
- Frontend/Views/Transfers/OutgoingTrustDetails.cshtml
- Add confirm outgoing trusts route
- Outgoing academies page
- Outgoing academies page
Part of the .NET rewrite of the Rails frontend adding in the page for selecting acadmies to be transfered
- Add route for confirming the outgoing academy trust
- Add route for displaying the acadmies beloinging to the outgoing trust
- Add route to store the selected academies in the session
> Add page for outgoing academies

- API.Tests/ControllersTests/AcademiesControllerTests.cs
- API.Tests/ControllersTests/ProjectsControllerTests.cs
- API.Tests/ControllersTests/TrustsControllerTests.cs
- API.Tests/RepositoriesTests/TrustsRepositoryTests.cs
- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- TRAMS-API/Controllers/ProjectsController.cs
- TRAMS-API/Controllers/TrustsController.cs
- TRAMS-API/Models/Upstream/Request/PostProjectsRequestModel.cs
- TRAMS-API/Repositories/Interfaces/IProjectsRepository.cs
- TRAMS-API/Repositories/Interfaces/ITrustsRepository.cs
- TRAMS-API/Repositories/ProjectsRepository.cs
- TRAMS-API/Repositories/TrustsRepository.cs
In preparation for swapping away from the TRAMS API, we have refactored any TRAMS domain objects (The ones containing D365) to be contained only within the implementations of the repositories. This means pivoting in the future should be much easier
- Refactor the project repository
- Refactor the trusts repository
> Refactor projects & trusts repo

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Views/Transfers/TrustName.cshtml
- TRAMS-API/Repositories/Interfaces/ITrustsRepository.cs
- TRAMS-API/Repositories/TrustsRepository.cs
Users need to be able to search for the outgoing trust and have a consistent experience with error messages to prevent them going to an empty search page.
- Add error message for no search query entered
- Add error message for no results found
- Support pre-filling the query box from the URL
> Outgoing Trust page error messages

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Views/Transfers/CheckYourAnswers.cshtml
- Frontend/Views/Transfers/IncomingTrust.cshtml
- Frontend/Views/Transfers/TrustName.cshtml
We need to provide error messages in the case of:
- No search query provided
- No results found
- Return an error in the case of no results found
- Return an error in the case of no query entered
- Pre-fill the search box with information entered in the case of an error
- Show the error inline with the GOV.UK Design System guidelines
- Support no incoming trust being selected
> Add error messages to incoming trust search page

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Views/Transfers/OutgoingTrustAcademies.cshtml
- Frontend/Views/Transfers/TrustName.cshtml
For our MVP we're only going to work on transfers that contain a single academy - to prevent users from selecting more than one academy we've changed the page for academy selection from checkboxes to radio buttons. 
Additionally, we need to prevent users from selecting _no_ academy, so this also adds validation.
- Change from checkboxes to radio buttons for academies
- Perform presence checking for academy selection
> Select a single academy

- Frontend/Views/Transfers/SearchIncomingTrust.cshtml
- Frontend/Views/Transfers/TrustSearch.cshtml
We want to make the search results page slightly more clear in the information displayed
- Update the layout for search results pages
> Update display of search results when searching for trusts

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Views/Shared/_Layout.cshtml
- Frontend/Views/Transfers/CheckYourAnswers.cshtml
- Frontend/Views/Transfers/IncomingTrust.cshtml
- Frontend/Views/Transfers/IncomingTrustDetails.cshtml
- Frontend/Views/Transfers/IncomingTrustIdentified.cshtml
- Frontend/Views/Transfers/OutgoingTrustAcademies.cshtml
- Frontend/Views/Transfers/OutgoingTrustDetails.cshtml
- Frontend/Views/Transfers/SearchIncomingTrust.cshtml
- Frontend/Views/Transfers/TrustName.cshtml
- Frontend/Views/Transfers/TrustSearch.cshtml
To allow users to navigate backwards through the service, they need to use GOV.UK Back links as per the service standard.
- Add back links to the service, supporting pre-filling the query where easily possible
> Add back links for transfer creation process

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Views/Transfers/CheckYourAnswers.cshtml
- Frontend/Views/Transfers/OutgoingTrustDetails.cshtml
- Frontend/Views/Transfers/TrustName.cshtml
- Frontend/Views/Transfers/TrustSearch.cshtml
Following the GOV.UK Design system - we have implemented change links on our "Check your answers page", as such we need to support these and handle the user navigation between them.
When changing an outgoing trust, we also want the user to go through the process again, and changing the outgoing trust is a fundamental change to the transfer.
- Update pages to support navigation from the change link page
- Clear the session when outgoing trusts are selected
> Implement change link functionality for outgoing trusts

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Views/Transfers/IncomingTrust.cshtml
For our MVP we are only allowing the creation of projects where the incoming trust is identified. As such, we are skipping the step in the creation process that lets you pick if an incoming trust is identified or not.
- Skip the incoming trust identified page
> Skip the incoming trust identified stage

- DocumentGeneration.Tests/DocumentBuilderHelpersTests.cs
- DocumentGeneration.Tests/DocumentBuilderTests.cs
- DocumentGeneration.Tests/DocumentGeneration.Tests.csproj
- DocumentGeneration.Tests/DocumentHeadingBuilderTests.cs
- DocumentGeneration.Tests/DocumentTableBuilderTests.cs
- DocumentGeneration/DocumentBuilder.cs
- DocumentGeneration/DocumentBuilderHelpers.cs
- DocumentGeneration/DocumentBuilderTextOptions.cs
- DocumentGeneration/DocumentGeneration.csproj
- DocumentGeneration/DocumentHeadingBuilder.cs
- DocumentGeneration/DocumentTableBuilder.cs
- DocumentGeneration/IDocumentBuilder.cs
- Frontend.Tests/ControllerTests/HeadteacherBoardControllerTests.cs
- Frontend.Tests/Frontend.Tests.csproj
- Frontend/Controllers/HeadteacherBoardController.cs
- Frontend/Controllers/HomeController.cs
- Frontend/Controllers/ProjectController.cs
- Frontend/Frontend.csproj
- Frontend/Services/CreateHtbDocument.cs
- Frontend/Services/ICreateHtbDocument.cs
- Frontend/Startup.cs
- Frontend/Views/HeadteacherBoard/Download.cshtml
- Frontend/Views/HeadteacherBoard/Preview.cshtml
- Frontend/Views/Home/Index.cshtml
- Frontend/Views/Project/Index.cshtml
- academy-transfers-api.sln
We want to support the creation of Word documents for our users to be able to edit further down the line, giving them a good starting point.
In the long run, the desire will be to move the `DocumentGeneration` project out to a separate library to be used across SDD - for the ease
of development now this is just a project internal to this.
- Add document generator with ability to add tables
- Quick initial workflow for downloading documents
- Support new lines in text
- Support headings in document generation
- Create HTB document download workflow
> Initial word document generation workflow

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Startup.cs
- TRAMS-API/Wrappers/DynamicsProjectWrapper.cs
We're migrating over to the planned TRAMS API - this moves the controller away from depending on the dynamics specific project interface, and to the new shared interface.
Additionally, as a result, there is some temporary code to map between ProjectId GUIDs (Dynamics) to Project URNs, and the relevant resources.
Once we've migrated, this code will be deleted, and as such has no tests.
- Create DynaimcsProjectWrapper for wrapping project calls
- Migrate transfers controller
> Migrate dynamics project creation to shared interface

- Data/Models/Project.cs
- Frontend.Tests/ControllerTests/ProjectControllerTests.cs
- Frontend/Controllers/ProjectController.cs
- TRAMS-API/Wrappers/DynamicsProjectWrapper.cs
In preparation for the new TRAMS API - We're migrating away from dynamics specific code within the `Frontend` repository, except for references to the `Wrapper` classes
Migrate project index to the dynamics wrapper
Update project model with project name and trust information
> Migrate project index to new interface

- Data.Mock/MockAcademyRepository.cs
- Data/Models/Academies/LatestOfstedJudgement.cs
- Data/Models/Academy.cs
- Data/Models/Trust.cs
- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Views/Transfers/CheckYourAnswers.cshtml
- Frontend/Views/Transfers/CheckYourAnswers.cshtml.cs
- Frontend/Views/Transfers/OutgoingTrustAcademies.cshtml
- Frontend/Views/Transfers/OutgoingTrustAcademies.cshtml.cs
- TRAMS-API/Wrappers/DynamicsTrustsWrapper.cs
As part of the work migrating to the new API
- Migrate away from using GetTrustAcademies to getting the Academies from the GetTrustByUKPRN
- Clean up transfers controller away from GUIDs
> Migrate get trust academies

- Data.Mock/MockProjectRepository.cs
- Data/Models/Project.cs
- Data/Models/Projects/TransferFeatures.cs
- Frontend.Tests/ControllerTests/Projects/TransferDatesControllerTests.cs
- Frontend.Tests/Helpers/ControllerTestHelpers.cs
- Frontend/Controllers/Projects/TransferDatesController.cs
- Frontend/Helpers/DatesHelper.cs
- Frontend/Models/TransferDatesViewModel.cs
- Frontend/Views/Features/Index.cshtml
- Frontend/Views/Project/Index.cshtml
- Frontend/Views/TransferDates/Index.cshtml
We want to record the dates relevant to the transfer of the academy. This PR is the first in creating the relevant pages for it
- Create the model for transfer dates
- Create summary page for transfer dates
- Add helper methods for handling date strings
> Add transfer dates summary page

- Frontend.Tests/ControllerTests/Projects/TransferDatesControllerTests.cs
- Frontend.Tests/Helpers/ControllerTestHelpers.cs
- Frontend.Tests/ModelTests/TransferDatesViewModelTests.cs
- Frontend/Controllers/Projects/TransferDatesController.cs
- Frontend/Frontend.csproj
- Frontend/Helpers/DatesHelper.cs
- Frontend/Models/FeaturesViewModel.cs
- Frontend/Models/Forms/DateInputViewModel.cs
- Frontend/Models/Forms/FormError.cs
- Frontend/Models/Forms/FormErrorsViewModel.cs
- Frontend/Models/Forms/RadioButtonViewModel.cs
- Frontend/Models/TransferDatesViewModel.cs
- Frontend/Views/Shared/_FormErrorSummary.cshtml
- Frontend/Views/Shared/_InlineRadioButtons.cshtml
- Frontend/Views/Shared/_RadioButtons.cshtml
- Frontend/Views/TransferDates/FirstDiscussed.cshtml
- Frontend/Views/TransferDates/Index.cshtml
Part of the work on adding transfer dates - this adds in the ability to set the date the transfer was first discussed with the trust
- Move form view models to forms folder
- Add transfer dates view model with tests
- Support posting valid date
- Validate first discussed date
> Create Transfer First Discussed pages

- Frontend.Tests/ControllerTests/Projects/TransferDatesControllerTests.cs
- Frontend/Controllers/Projects/TransferDatesController.cs
- Frontend/Helpers/DatesHelper.cs
- Frontend/Views/TransferDates/Index.cshtml
- Frontend/Views/TransferDates/TargetDate.cshtml
Allows our users to enter the target date for the transfer to take place
- Add target date for transfer page
- Link to target date from summary page
> Add Target Dates for transfer page

- Data.Mock/MockProjectRepository.cs
Due to how mock projects were stored/retreived - when you got a project by URN it would return the stored project, allowing you to edit it directly. This caused errors as it would update the stored project with invalid data.
Return a cloned project from the MockProjectRepository
> Ensure mock projects are clones of the stored projects

- Data.Mock/MockProjectRepository.cs
- Data/Models/Project.cs
- Data/Models/Projects/TransferBenefits.cs
- Data/Models/Projects/TransferDates.cs
- Data/Models/Projects/TransferRationale.cs
- Frontend.Tests/ControllerTests/Projects/BenefitsControllerTests.cs
- Frontend.Tests/ControllerTests/Projects/TransferDatesControllerTests.cs
- Frontend.Tests/ModelTests/BenefitsViewModelTests.cs
- Frontend.Tests/ModelTests/TransferDatesViewModelTests.cs
- Frontend/Controllers/Projects/BenefitsController.cs
- Frontend/Controllers/Projects/TransferDatesController.cs
- Frontend/Models/BenefitsViewModel.cs
- Frontend/Models/TransferDatesViewModel.cs
- Frontend/Views/Benefits/Index.cshtml
- Frontend/Views/Benefits/IntendedBenefits.cshtml
- Frontend/Views/Benefits/OtherFactors.cshtml
- Frontend/Views/TransferDates/HtbDate.cshtml
- Frontend/Views/TransferDates/Index.cshtml
In preparation for adding a new editable section - this PR adds a new field to the Project model.
Additionally, this cleans up some redundant naming on fields in the project model
- Add Rationale field to project
- Remove "Transfer" from the names of fields that it was redundant on
> Add project rationale to data model

- Frontend/Views/Rationale/Index.cshtml
Rationale's are typically quite lengthy, in order to ease reading this we want to increase the width of the column they're displayed in
- Add Govuk full width classes to the rationales in the summary list
> Increase width of rationale display

- Data.Mock/MockProjectRepository.cs
- Data.TRAMS.Tests/TramsAcademiesRepositoryTests.cs
- Data.TRAMS/Models/AcademyTransferProjectFeatures.cs
- Data.TRAMS/Models/Census.cs
- Data.TRAMS/Models/GroupContactAddress.cs
- Data.TRAMS/Models/MisEstablishment.cs
- Data.TRAMS/Models/Misfea.cs
- Data.TRAMS/Models/Provider.cs
- Data.TRAMS/Models/SmartData.cs
- Data.TRAMS/Models/TramsAcademy.cs
- Data.TRAMS/Models/TramsProject.cs
- Data.TRAMS/Models/TramsTrust.cs
- Data.TRAMS/Models/TramsTrustGiasData.cs
- Data.TRAMS/Models/TramsTrustIfdData.cs
- Data.TRAMS/Models/TramsTrustSearchAcademy.cs
- Data.TRAMS/Models/TramsTrustSearchResult.cs
- Data.TRAMS/Models/TransferringAcademy.cs
- Data.TRAMS/TramsAcademiesRepository.cs
- Frontend/Startup.cs
The API spec changed recently to not be camel case, this PR brings the API classes in line with the new specification by removing the JSON Property fields
- Fix TRAMS Api class setups
- Remove JSONProperties
> Update API Classes to match current naming

- Frontend/Views/Transfers/SearchIncomingTrust.cshtml
- Frontend/Views/Transfers/TrustSearch.cshtml
Update the incoming trust links displayed on the search-incoming-trust page to be radio buttons
- Update links to be radio buttons
- Amend title size
- Add URN in brackets after the trust name
> Change trust links to radio buttons on search-incoming-trust page

- Data.TRAMS.Tests/Mappers/Response/TramsEstablishmentMapperTests.cs
- Data.TRAMS.Tests/Mappers/Response/TramsSearchResultMapperTests.cs
- Data.TRAMS.Tests/Mappers/Response/TramsTrustMapperTests.cs
- Data.TRAMS.Tests/TestFixtures/Establishments.cs
- Data.TRAMS.Tests/TestFixtures/TrustSearchResults.cs
- Data.TRAMS.Tests/TestFixtures/Trusts.cs
- Data.TRAMS.Tests/TramsAcademiesRepositoryTests.cs
- Data.TRAMS/Mappers/Response/TramsEstablishmentMapper.cs
- Data.TRAMS/Mappers/Response/TramsSearchResultMapper.cs
- Data.TRAMS/Mappers/Response/TramsTrustMapper.cs
- Data.TRAMS/Models/TramsEstablishment.cs
- Data.TRAMS/Models/TramsTrust.cs
- Data.TRAMS/Models/TramsTrustGiasData.cs
- Data.TRAMS/Models/TramsTrustSearchEstablishment.cs
- Data.TRAMS/Models/TramsTrustSearchResult.cs
- Data.TRAMS/TramsEstablishmentRepository.cs
- Data/Models/TrustSearchResult.cs
- Frontend/Startup.cs
The TRAMS API is now available and as such we can begin the work to map trusts against available data and populate it where required.
In addition, this update some naming conventions to be in line with the TRAMS API
- Rename TRAMS Academy references to Establishments
- Map TRAMS Trust data
> Map TRAMS trusts from API

- Frontend.Tests/ControllerTests/Projects/TransferDatesControllerTests.cs
- Frontend.Tests/ModelTests/TransferDatesViewModelTests.cs
- Frontend/Controllers/Projects/TransferDatesController.cs
- Frontend/Models/TransferDatesViewModel.cs
- Frontend/Views/TransferDates/HtbDate.cshtml
User research showed that pre-populated HTB Dates would be too restrictive, as they can differ per region. As such, we're moving to allow manual entry
- Align HTB Date entry with other date entry fields
> Allow users to manually enter an HTB Date

- Data.Mock/MockProjectRepository.cs
- Data/Models/Project.cs
- Data/Models/Projects/TransferringAcademies.cs
- Frontend/Views/AcademyPerformance/Index.cshtml
- Frontend/Views/Benefits/Index.cshtml
- Frontend/Views/Benefits/IntendedBenefits.cshtml
- Frontend/Views/Benefits/OtherFactors.cshtml
- Frontend/Views/Features/Index.cshtml
- Frontend/Views/Features/Initiated.cshtml
- Frontend/Views/Features/Reason.cshtml
- Frontend/Views/Features/Type.cshtml
- Frontend/Views/Home/Index.cshtml
- Frontend/Views/LatestOfstedJudgement/Index.cshtml
- Frontend/Views/Project/Index.cshtml
- Frontend/Views/PupilNumbers/Index.cshtml
- Frontend/Views/Rationale/Index.cshtml
- Frontend/Views/Rationale/Project.cshtml
- Frontend/Views/Rationale/TrustOrSponsor.cshtml
- Frontend/Views/TransferDates/FirstDiscussed.cshtml
- Frontend/Views/TransferDates/HtbDate.cshtml
- Frontend/Views/TransferDates/Index.cshtml
- Frontend/Views/TransferDates/TargetDate.cshtml
As we're developing these services in line with each other, we're updating our content to bring it inline with the Academy Conversions team
- Display URN on Home page
- Display URN on the task list
- Add URNs to summary pages
- Add outgoing academy name to data entry pages
- Update continue button text on summary pages
- Update task list based on prototype
> Align content with Academy Conversions

- Frontend/Views/Benefits/Index.cshtml
- Frontend/Views/Features/Index.cshtml
- Frontend/Views/TransferDates/Index.cshtml
This is old content that is no longer relevant and as such has been removed
- Remove intro paragraphs from summary pages
> Remove intro paragraphs from summary pages

- Frontend/Views/HeadteacherBoard/Download.cshtml
- Frontend/Views/Project/Index.cshtml
Users mentioned in user research that they may not always wish to preview the HTB template, as such we're adding a secondary action to immeditely jump to the download page
- Update Task List Call to action
> Update task list call to action

- Data.TRAMS.Tests/TramsTrustsRepositoryTests.cs
- Data.TRAMS/TramsProjectsRepository.cs
- Data.TRAMS/TramsTrustsRepository.cs
- Frontend/Views/Transfers/IncomingTrust.cshtml
- Frontend/Views/Transfers/TrustName.cshtml
The TRAMS API currently does not have an implemented trust search with the performance necessary to use. To allow us to launch in case this isn't ready in time, we decided to implement a "Search by UKPRN" only workaround utalising the `trust/ukprn` endpoint
- Add interim workaround for searching trusts
- Update content to reflect current search info
> Search by UKPRN Workaround

- Frontend/Views/LatestOfstedJudgement/Index.cshtml
Some sections of the page were displayed with different margins
Adjust style margins in Ofsted summary page
> Adjust style in Ofsted summary page

- DocumentGeneration.Tests/DocumentBuilderTests.cs
- DocumentGeneration/Builders/BulletedListBuilder.cs
- DocumentGeneration/Builders/NumberedListBuilder.cs
- DocumentGeneration/Builders/ParagraphBuilder.cs
- DocumentGeneration/DocumentBuilder.cs
- DocumentGeneration/Elements/TextElement.cs
- DocumentGeneration/Interfaces/IDocumentBuilder.cs
- DocumentGeneration/Interfaces/IListBuilder.cs
- Frontend/Services/CreateHtbDocument.cs
Future iterations of HTB templates will be using the MOJ Rich text editor, which supports users adding lists (with bold/italic/underlined text), as such we wanted to add support in now
- Add support for single level numbered lists
- Add support for single level bulleted lists
> Support lists in document generation

- DocumentGeneration.Tests/DocumentBuilderTests.cs
- DocumentGeneration.Tests/Helpers/HtmlToDocumentTests.cs
- DocumentGeneration/Builders/BulletedListBuilder.cs
- DocumentGeneration/Builders/ListBuilder.cs
- DocumentGeneration/Builders/NumberedListBuilder.cs
- DocumentGeneration/Builders/ParagraphBuilder.cs
- DocumentGeneration/Helpers/HtmlToDocument.cs
- DocumentGeneration/Interfaces/IDocumentBuilder.cs
- DocumentGeneration/Interfaces/IListBuilder.cs
- DocumentGeneration/Interfaces/IParagraphBuilder.cs
- DocumentGeneration/README.md
- Frontend/Services/CreateHtbDocument.cs
In the future services will use the [MOJ Rich Text editor](https://moj-design-system.herokuapp.com/components/rich-text-editor) to enter certain fields. This stores data as HTML and as such we need to supportt
- Add HTML to document converter
- Add README for document generation
- Fix lists not displaying correctly in microsoft word
> Allow HTML text to be added to word documents

- Data.Mock/MockProjectRepository.cs
- Data.TRAMS.Tests/Mappers/Request/InternalProjectToUpdateMapperTests.cs
- Data.TRAMS.Tests/Mappers/Response/TramsProjectMapperTests.cs
- Data.TRAMS/Mappers/Request/InternalProjectToUpdateMapper.cs
- Data.TRAMS/Mappers/Response/TramsProjectMapper.cs
- Data.TRAMS/Models/AcademyTransferProject/AcademyTransferProjectAcademyAndTrustInformation.cs
- Data.TRAMS/Models/TramsProject.cs
- Data.TRAMS/Models/TramsProjectUpdate.cs
- Data/Models/Project.cs
- Data/Models/Projects/TransferAcademyAndTrustInformation.cs
- Frontend.Tests/ControllerTests/Projects/AcademyAndTrustInformationControllerTests.cs
- Frontend.Tests/ModelTests/ProjectTaskListViewModelTests.cs
- Frontend/Controllers/Projects/AcademyAndTrustInformationController.cs
- Frontend/Models/AcademyAndTrustInformationViewModel.cs
- Frontend/Models/ProjectTaskListViewModel.cs
- Frontend/Views/AcademyAndTrustInformation/Index.cshtml
- Frontend/Views/AcademyAndTrustInformation/Recommendation.cshtml
- Frontend/Views/Project/Index.cshtml
Add academy and trust information page
Add fields to project and trams api models to support author and recommendation fields
Add academy and trust information page
Add ability to edit recommendation and author
> Add academy and trust information page

- Data.TRAMS/TramsProjectsRepository.cs
- Frontend.Tests/ControllerTests/Projects/AcademyAndTrustInformationControllerTests.cs
- Frontend.Tests/ModelTests/AcademyAndTrustInformationViewModelTests.cs
- Frontend/Controllers/Projects/AcademyAndTrustInformationController.cs
- Frontend/Views/AcademyAndTrustInformation/Index.cshtml
- Frontend/wwwroot/src/css/site.scss
Link the reference fields to the TRAMS API for the reference section of the academy and trust information page
Add correct TRAMS API fields to the reference data displayed in the academy and trust information page
> Add reference fields to academy and trust information page

- Frontend/Views/AcademyAndTrustInformation/Index.cshtml
Correct formatting of dates on academy and trust information page
When dates are shown on the page, display as D MMM YYYY (e.g. 1 September 2021) rather than 01/09/2021
> Correct formatting of dates on academy and trust information page

- Frontend.Tests/HelpersTests/PerformanceDataHelpersTests.cs
- Frontend/Helpers/PerformanceDataHelpers.cs
- Frontend/Pages/KeyStage2Performance.cshtml
Add helper to format performance results
Format results so where no data is returned "no data" is displayed on the page
Show whole number decimals with no decimal places
> Add helper to format performance results

- Data.TRAMS.Tests/Mappers/Response/TramsEducationPerformanceMapperTests.cs
- Data.TRAMS.Tests/TestFixtures/EducationPerformance.cs
- Data.TRAMS/Mappers/Response/TramsEducationPerformanceMapper.cs
- Data.TRAMS/Models/EducationPerformance/KeyStage5.cs
- Data.TRAMS/Models/EducationPerformance/TramsEducationPerformance.cs
- Data/Models/KeyStagePerformance/EducationPerformance.cs
- Data/Models/KeyStagePerformance/KeyStage5.cs
- Data/Models/KeyStagePerformance/KeyStage5Result.cs
- Frontend.Tests/ModelTests/ProjectTaskListViewModelTests.cs
- Frontend.Tests/PagesTests/KeyStage5PerformanceTests.cs
- Frontend/Controllers/ProjectController.cs
- Frontend/Models/ProjectTaskListViewModel.cs
- Frontend/Pages/KeyStage5Performance.cshtml
- Frontend/Pages/KeyStage5Performance.cshtml.cs
- Frontend/Views/Project/Index.cshtml
We want to be able to display the Key stage 5 performance information provided by the TRAMS api
- Integrate with key stage 5 performance information
- Display key stage 5 performance information
> Key stage 5 performance information

- Frontend.Tests/ModelTests/ProjectTaskListViewModelTests.cs
- Frontend/Models/ProjectTaskListViewModel.cs
- Frontend/Pages/KeyStage5Performance.cshtml
It turns out KS5 data is similar to other data wherein it appears for schools that aren't appropriate
- Fix link to compare school service
- show/hide KS5 data correctly
> Show/Hide KS5 data corrextly

- Frontend.Tests/HelpersTests/PerformanceDataHelpersTests.cs
- Frontend.Tests/PagesTests/KeyStage4PerformanceTests.cs
- Frontend/Helpers/PerformanceDataHelpers.cs
- Frontend/Pages/TaskList/KeyStage2Performance/KeyStage2Performance.cshtml
- Frontend/Pages/TaskList/KeyStage4Performance/KeyStage4Performance.cshtml
- Frontend/Pages/TaskList/KeyStage4Performance/KeyStage4Performance.cshtml.cs
- Frontend/Pages/TaskList/KeyStage5Performance/KeyStage5Performance.cshtml
- Frontend/Views/Project/Index.cshtml
Fixes to the performance table pages
Format the year to include a space in between years (e.g. 2018 - 2019)
Fix bug with KS4 page where it was using KS2 additional information field
Fix KS4 page formatting of confidence interval level
> Performance table fixes

- Frontend.Tests/HelpersTests/TagHelperTests/BackToPreviewPageTagHelperTests.cs
- Frontend.Tests/PagesTests/TaskList/KeyStage2PerformanceTests.cs
- Frontend.Tests/PagesTests/TaskList/KeyStage4PerformanceTests.cs
- Frontend.Tests/PagesTests/TaskList/KeyStage5PerformanceTests.cs
- Frontend/Helpers/TagHelpers/BackToPreviewPageTagHelper.cs
- Frontend/Models/Forms/AdditionalInformationViewModel.cs
- Frontend/Models/Links.cs
- Frontend/Pages/TaskList/HtbDocument/KeyStage2PerformanceSummary.cshtml
- Frontend/Pages/TaskList/HtbDocument/KeyStage4PerformanceSummary.cshtml
- Frontend/Pages/TaskList/HtbDocument/KeyStage5PerformanceSummary.cshtml
- Frontend/Pages/TaskList/KeyStage2Performance/KeyStage2Performance.cshtml
- Frontend/Pages/TaskList/KeyStage2Performance/KeyStage2Performance.cshtml.cs
- Frontend/Pages/TaskList/KeyStage4Performance/KeyStage4Performance.cshtml
- Frontend/Pages/TaskList/KeyStage4Performance/KeyStage4Performance.cshtml.cs
- Frontend/Pages/TaskList/KeyStage5Performance/KeyStage5Performance.cshtml
- Frontend/Pages/TaskList/KeyStage5Performance/KeyStage5Performance.cshtml.cs
- Frontend/Views/Shared/_AdditionalInformation.cshtml
The HTB preview page has change links for certain fields, as such when the user clicks on them we need to update navigation to correctly point/redirect as appropriate
- Add a tag helper for going back to the preview page
- Add redirects to the additional information for key stage performance data
> HTB Preview - Education performance change links

- Data.Mock/MockProjectRepository.cs
- Data.TRAMS.Tests/TramsProjectsRepositoryTests.cs
- Data.TRAMS/TramsProjectsRepository.cs
- Data/IProjects.cs
- Frontend.Tests/ControllerTests/HomeControllerTests.cs
- Frontend/Controllers/HomeController.cs
- Frontend/Views/Home/Index.cshtml
- Frontend/Views/Home/Index.cshtml.cs
For performance, the API only returns the first 10 items from the academy transfer project endpoint, however when there is more there is currently no way to know.
Until there's meta data added to the endpoint, this will check for 10 items, and if there is 10 it will display the "next page" button, otherwise it will not.
- Add page param to `academytransferproject` endpoint query
- Add MoJ pagination to project list
> Support basic pagination on home screen

- .github/workflows/build_test_deploy.yml
- Frontend/Views/GeneralInformation/Index.cshtml
This text is no longer necessary
- Hides the general information additional information field
> Hide additional information on general info page

- Data.TRAMS.Tests/Mappers/Response/TramsEstablishmentMapperTests.cs
- Data.TRAMS/Mappers/Response/TramsEstablishmentMapper.cs
- Data.TRAMS/Models/TramsEstablishment.cs
- Data.TRAMS/Models/ViewAcademyConversion.cs
The ability to populate new fields from the API has been added, as such we need to map those fields to our internal models
- Maps data from the `viewAcademyTransfer` field on the API to the general information for the academy
> Integrate with additional general information data

- Frontend.Tests/HelpersTests/PerformanceDataHelpersTests.cs
- Frontend.Tests/PagesTests/TaskList/KeyStage4PerformanceTests.cs
- Frontend/Helpers/PerformanceDataHelpers.cs
- Frontend/Pages/TaskList/KeyStage2Performance/KeyStage2PerformanceTables.cshtml
- Frontend/Pages/TaskList/KeyStage4Performance/KeyStage4Performance.cshtml
- Frontend/Pages/TaskList/KeyStage4Performance/KeyStage4Performance.cshtml.cs
- Frontend/Pages/TaskList/KeyStage4Performance/KeyStage4PerformanceTables.cshtml
- Frontend/Pages/TaskList/KeyStage5Performance/KeyStage5PerformanceTables.cshtml
- Frontend/Services/CreateHtbDocument.cs
- Frontend/Services/GetHtbDocumentForProject.cs
Update year data in performance sections
Update year to read for example 2018 to 2019 instead of 2018-2019
Change order of KS4 years to show most recent first
Insert calculated year for those schools with no data for that year in ks4 data
> Update years in performance pages

- Frontend/Views/GeneralInformation/Index.cshtml
- Frontend/Views/PupilNumbers/Index.cshtml
AT does not have an application form, so this is irrelevant
- Remove content that's no longer relevant referencing the application form
> Remove application form content from help text

- Frontend.Tests/ModelTests/FormsTests/FormErrorsViewModelTests.cs
- Frontend/Models/Forms/FormErrorsViewModel.cs
- Frontend/Views/Benefits/IntendedBenefits.cshtml
- Frontend/Views/Benefits/OtherFactors.cshtml
- Frontend/Views/Features/Initiated.cshtml
- Frontend/Views/Features/Reason.cshtml
- Frontend/Views/Features/Type.cshtml
- Frontend/Views/Rationale/Project.cshtml
- Frontend/Views/Rationale/TrustOrSponsor.cshtml
- Frontend/Views/TransferDates/FirstDiscussed.cshtml
- Frontend/Views/TransferDates/HtbDate.cshtml
- Frontend/Views/TransferDates/TargetDate.cshtml
- Frontend/Views/Transfers/IncomingTrust.cshtml
- Frontend/Views/Transfers/OutgoingTrustAcademies.cshtml
- Frontend/Views/Transfers/TrustName.cshtml
Add Error to page title when there is an error (this was flagged as an issue in Accessibility report
Add error to relevant pages where an error can occur
> Accessibility: Add Error to page title on error

- Frontend/Views/Benefits/IntendedBenefits.cshtml
- Frontend/Views/Benefits/OtherFactors.cshtml
- Frontend/Views/Features/Type.cshtml
- Frontend/Views/HeadteacherBoard/Download.cshtml
- Frontend/Views/Project/Index.cshtml
- Frontend/Views/Shared/_Layout.cshtml
- Frontend/Views/TransferDates/HtbDate.cshtml
- Frontend/Views/Transfers/OutgoingTrustAcademies.cshtml
- Frontend/Views/Transfers/TrustSearch.cshtml
Some page titles have become out of sync of the heading, ensure the page title matches the h1 heading
Update all page titles to match heading
Remove Gov.Uk from page title
Amend `transfer and academy` to `manage an academy` in the page title
> Update page titles

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Views/Transfers/SearchIncomingTrust.cshtml
Show error if no incoming trust is selected on search page
Show error if no incoming trust is selected on search page
> Show error if no incoming trust is selected on search page

- Data.TRAMS.Tests/Mappers/Request/InternalProjectToUpdateMapperTests.cs
- Data.TRAMS/Mappers/Request/InternalProjectToUpdateMapper.cs
- Data.TRAMS/Models/AcademyTransferProject/AcademyTransferProjectDates.cs
- Frontend.Tests/ControllerTests/Projects/TransferDatesControllerTests.cs
- Frontend/Controllers/Projects/TransferDatesController.cs
- Helpers.Tests/DatesHelperTests.cs
- Helpers/DatesHelper.cs
Allow users to set the Htb, transfer and discussed date back to null after they have been set
Update Trams API to allow the Htb, transfer and discussed date to be set back to null
Update AT service to remove required validation and set and send extra fields to trams api
> Allow empty date fields

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Helpers/Session.cs
- Frontend/Startup.cs
- Frontend/Views/Transfers/CheckYourAnswers.cshtml
If more than double clicks are sent the session values can be null
Handle session null values gracefully
> Feature 85762 - Check session is still valid before creating project

- Frontend/Pages/TaskList/HtbDocument/Preview.cshtml
On the preview page, we can take advantage of column wrapping in order to simplify the layout and reduce the number of `govuk-grid-row` wrappers.
- Use single row for layout on the preview page
> Use single row for layout

- Data.TRAMS.Tests/Data.TRAMS.Tests.csproj
We need the `xunit.runner.visualstudio` package to run tests in Visual Studio. We've already included it in most of the test projects, but it's missing in the TRAMS tests.
- Make sure TRAMS test project runs in Visual Studio
> Make sure TRAMS test project runs in Visual Studio

- Frontend/Helpers/TagHelpers/ProjectStatusTagHelper.cs
- Frontend/Pages/Projects/Index.cshtml
- Frontend/wwwroot/src/js/google-analytics-events.js
- Frontend/wwwroot/webpack.config.js
Spike. We want to know which sections have been completed when the project template is downloaded. This isn't captured by GTM out-of-the-box, so we need to add a custom event.
Add custom Google Tag Manager event when project template downloaded: Add data attributes to the section statuses and generate button in order to build and dispatch the custom event. This also reconfigures Webpack so that we can add multiple JavaScript files.
> Add custom Google Tag Manager event when project template downloaded AB#90214

- Frontend/Views/Shared/_Layout.cshtml
The Webpack configuration was updated in the previous PR, using the `main` key for `site.js`.
I forgot to update the src of the script in the main layout file.
- Fix src for main Webpack bundle
> Fix src for main Webpack bundle

- Frontend.Tests/HelpersTests/TagHelperTests/GdsKeyValueTagHelperTests.cs
- Frontend.Tests/HelpersTests/TagHelperTests/GdsValidationSummaryTagHelperTests.cs
- Frontend/Helpers/TagHelpers/GdsKeyValueTagHelper.cs
- Frontend/Helpers/TagHelpers/GdsValidationForTagHelper.cs
- Frontend/Helpers/TagHelpers/GdsValidationSummaryTagHelper.cs
- Frontend/Pages/Projects/BenefitsAndRisks/IntendedBenefits.cshtml
- Frontend/Pages/Projects/BenefitsAndRisks/Risks.cshtml
- Frontend/Pages/Projects/Features/Initiated.cshtml
- Frontend/Pages/Projects/Features/Reason.cshtml
- Frontend/Pages/Projects/Features/Type.cshtml
- Frontend/Pages/Projects/Rationale/Project.cshtml
- Frontend/Pages/Projects/Rationale/TrustOrSponsor.cshtml
- Frontend/Pages/Projects/TransferDates/AdvisoryBoard.cshtml
- Frontend/Pages/Projects/TransferDates/FirstDiscussed.cshtml
- Frontend/Pages/Projects/TransferDates/Target.cshtml
- Frontend/Pages/Shared/_AcademyAndTrustSummary.cshtml
- Frontend/Pages/Transfers/CheckYourAnswers.cshtml
- Frontend/Pages/Transfers/IncomingTrust.cshtml
- Frontend/Pages/Transfers/OutgoingTrustAcademies.cshtml
- Frontend/Pages/Transfers/SearchIncomingTrust.cshtml
- Frontend/Pages/Transfers/TrustName.cshtml
- Frontend/Pages/Transfers/TrustSearch.cshtml
- Frontend/Views/Shared/_FormErrorSummary.cshtml
- Frontend/Views/Shared/_Layout.cshtml
- Frontend/wwwroot/package-lock.json
- Frontend/wwwroot/package.json
Update to GOV.UK frontend 4
- Remove `tabindex` from error summary: Applying tabindex to the error summary means that it takes focus when clicked. The frontend team now handle the error summary focus in JavaScript to prevent this behaviour, and recommend we remove the attribute.
- Add data-module attribute to skip link: The GOV.UK frontend team have improved the skip link by adding JavaScript to assist screen readers. Update the skip link by adding the new attribute.
- Update error message element type: Follow the latest GOV.UK frontend advice and use a `p` tag for error messages, which is more semantically correct.
- Fix footer appearance: The footer component has been updated to align with the grid system. Set grid classes on `govuk-footer__section` to make sure footer appearance is as …
> Gov frontend 4

- Frontend/wwwroot/src/css/site.scss
We want to opt-in to the new style of hover links to match our prototype app. 
Enable links with clearer hover state: These aren't enabled by default in case any custom link styles need to be updated, but we are good to go ahead with them.
> Enable links with clearer hover state

- Data/Models/Projects/TransferBenefits.cs
- Frontend.Tests/ServicesTests/GetProjectTemplateModelTests.cs
- Frontend.Tests/TestFixtures/GetInformationForProject.cs
- Frontend/Pages/Projects/BenefitsAndRisks/ComplexLandAndBuilding.cshtml
- Frontend/Pages/Projects/BenefitsAndRisks/FinanceAndDebt.cshtml
- Frontend/Pages/Projects/BenefitsAndRisks/HighProfileTransfer.cshtml
- Frontend/Pages/Projects/BenefitsAndRisks/OtherRisks.cshtml
Content changes for benefits and risks
Remove (ministers and media could be involved) from the What are the risks? page
Add this hint text to the Why is this a high profile transfer? page: For example, ministers and media could be involved
Remove (ministers and media could be involved) from the summary page
Re-order the risk checklist items in alphabetical order on the What are the risks? page. This is based on GOV.UK Design System guidance.
Add unique titles to the conditional risk pages, such as Why is this a high profile transfer?. I recommend these titles:
High profile transfer
Complex land and building issues
Finance and debt concerns
Other risks
> Updates to benefits and risks summary #AB87228

- Frontend/Pages/Projects/TransferDates/Target.cshtml
- Frontend/Pages/Shared/_TransferDatesSummary.cshtml
Update "target" date for transfer to "expected": We want to remove the word "target" because delivery officers find it too rigid, replacing it with "expected" instead.
Remove the day field of the expected transfer date: Transfers always happen on the 1st of the month, so we've been recommended to remove the day field.
> "target" to "expected" and remove day field

- Frontend.Tests/PagesTests/Projects/TransferDates/TargetTests.cs
- Frontend/Pages/Projects/TransferDates/Target.cshtml
- Frontend/Pages/Projects/TransferDates/Target.cshtml.cs
- Frontend/Startup.cs
**Prevent target date validation being called twice:**
Currently, the TargetDateValidator gets called twice. The first time it gets executed by fluentvalidation's automatic integration and returns early, then later it's called explicitly with some additional context.
To prevent this we can exclude certain validators from being automatically registered in Startup - exclude the TargetDateValidator.
**Fix date validation:**
We want the expected date of transfer to always be the first of the month.
I was previously setting the day property unconditionally, which meant that the validation was returning an "invalid date" message, instead of a "required field" message when the other fields were empty.
To fix - conditionally set day only if month and year are also set.
> Fix date validation AB#93306

- Frontend/Pages/AccessibilityStatement.cshtml
Update accessibility statement on Transfers
DevOps ticket: https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_sprints/taskboard/Prepare%20conversions%20and%20transfers/Academies-and-Free-Schools-SIP/Manage%20an%20academy%20transfer/Sprint%2038?workitem=100681
- Updated content on a11y statement page so it is the same as the one on Conversions.
> 100681/Update Transfers accessibility statement 

- Frontend/Models/Forms/AdditionalInformationViewModel.cs
- Frontend/Pages/Projects/LatestOfstedJudgement/Index.cshtml.cs
- Frontend/Pages/Projects/PupilNumbers.cshtml.cs
- Frontend/Pages/TaskList/KeyStage2Performance/KeyStage2Performance.cshtml
- Frontend/Pages/TaskList/KeyStage2Performance/KeyStage2Performance.cshtml.cs
- Frontend/Pages/TaskList/KeyStage4Performance/KeyStage4Performance.cshtml
- Frontend/Pages/TaskList/KeyStage4Performance/KeyStage4Performance.cshtml.cs
- Frontend/Pages/TaskList/KeyStage5Performance/KeyStage5Performance.cshtml
- Frontend/Pages/TaskList/KeyStage5Performance/KeyStage5Performance.cshtml.cs
- Frontend/Views/Shared/_AdditionalInformation.cshtml
Updated content on key stage data pages for Transfers
DevOps ticket: https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_sprints/taskboard/Prepare%20conversions%20and%20transfers/Academies-and-Free-Schools-SIP/Manage%20an%20academy%20transfer/Sprint%2040?workitem=105288
- Updated content on key stage data pages for Transfers
> Task 105288 - Update key stage data content for Transfers

- Frontend/wwwroot/src/css/site.scss
Fixing project list content alignment for Transfers
DevOps ticket: https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_sprints/taskboard/Prepare%20conversions%20and%20transfers/Academies-and-Free-Schools-SIP/Manage%20an%20academy%20transfer/Sprint%2040?workitem=107871
- Fixing project list content alignment for Transfers to make the columns 60% + 40%
> 107871 Fixing project list content alignment for Transfers

- end-to-end-tests/cypress/e2e/cookie-policy/110944_cookies-policy.cy.js
- end-to-end-tests/cypress/support/commands.js
This PR covers the cookie policy for Transfers. Covering the cookie banner and cookie link in the footer functionality as covered in Conversions.
> Cookie policy for Transfers

- Frontend/Pages/Shared/_CookieBanner.cshtml
- end-to-end-tests/cypress/e2e/cookie-policy/107471_cookie-policy-content.cy.js
This PR covers the verification of Cookie links for Transfers, it's text as well as the redirection of the links.
Also added a selector to cshtml file (The related test will pass once the changes are merged to Dev env. )
> Verify Transfers cookie links and content

- end-to-end-tests/cypress/e2e/cookie-policy/107471_cookie-policy-content.cy.js
This PR fixing Cypress test which was failing due to incorrect redirection link issue
> Fix redirection issue

- Frontend.Tests/HelpersTests/TagHelperTests/GdsValidationSummaryTagHelperTests.cs
- Frontend/Helpers/TagHelpers/GdsValidationSummaryTagHelper.cs
- Frontend/Views/Shared/_FormErrorSummary.cshtml
Fixing accessibility issue: error messages not read aloud
DevOps ticket: https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_sprints/taskboard/Prepare%20conversions%20and%20transfers/Academies-and-Free-Schools-SIP/Manage%20an%20academy%20transfer/Sprint%2040?workitem=97087
- fixing markup structure for error summary in Transfers
> 97087 Fixing accessibility issue: error messages not read aloud

- end-to-end-tests/cypress/e2e/x-xss-protection/113746_disable_x-xss-protection.cy.js
This PR verifies if x-xss protect is disabled for transfers.
The HTTP X-XSS-Protection response header is a feature of Internet Explorer, Chrome and Safari that stops pages from loading when they detect reflected cross-site scripting (XSS) attacks.
> Disable x-xss protection header

- Frontend.Tests/PagesTests/Transfers/OutgoingTrustDetailsTests.cs
- Frontend.Tests/ValidatorTests/Transfers/IncomingTrustConfirmValidatorTests.cs
- Frontend.Tests/ValidatorTests/Transfers/OutgoingTrustConfirmValidatorTests.cs
- Frontend/Pages/Transfers/SearchIncomingTrust.cshtml
- Frontend/Validators/Transfers/IncomingTrustConfirmValidator.cs
- Frontend/Validators/Transfers/OutgoingTrustConfirmValidator.cs
- end-to-end-tests/cypress/e2e/End2EndTests/project-runthrough.cy.js
- end-to-end-tests/cypress/e2e/Performance/preview and download template.cy.js
- end-to-end-tests/cypress/support/commands.js
Updating error messages for the Incoming Trust page and Outgoing Trust page so that they are no longer the same as the page titles. Also we decided to rename the page title of Incoming Trust page to make it consistent with the Outgoing Trust page. 
You may have noticed that the error message of the Incoming Trust page is missing from the area above radio buttons. It will be fixed in a separate ticket. 
DevOps ticket: https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_sprints/taskboard/Prepare%20conversions%20and%20transfers/Academies-and-Free-Schools-SIP/Manage%20an%20academy%20transfer/Sprint%2040?workitem=100529
- Updated error messages for outgoing trust
- Updated error messages and page title for incoming trust
> 100529 Accessibility issue: select the trust

- Frontend/Pages/AccessibilityStatement.cshtml
Update content on the accessibility statement page on Transfers
- Update non-compliances
- Change WCAG to Web Content Accessibility Guidelines
DevOps ticket: 
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_sprints/taskboard/Prepare%20conversions%20and%20transfers/Academies-and-Free-Schools-SIP/Manage%20an%20academy%20transfer/Sprint%2040?workitem=115304
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_sprints/taskboard/Prepare%20conversions%20and%20transfers/Academies-and-Free-Schools-SIP/Manage%20an%20academy%20transfer/Sprint%2040?workitem=115307
- updated the non compliances paragraph
- Change WCAG to Web Content Accessibility Guidelines
> 115304 update accessibility statement for Transfers

- Frontend/Pages/AccessibilityStatement.cshtml
Update content on the accessibility statement page on Transfers
DevOps ticket: 
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_sprints/taskboard/Prepare%20conversions%20and%20transfers/Academies-and-Free-Schools-SIP/Manage%20an%20academy%20transfer/Sprint%2040?workitem=116312
- update content on the accessibility statement page on Transfers
> 116312 Updating accessibility statement for transfers

- end-to-end-tests/cypress/e2e/error-messages/target-date.cy.js
This PR fixing the 'target date' tests for dev and staging. It was failing a due to the multiple element error
> Target date fix for dev and staging

- .github/workflows/build-and-push-image-development.yml
This change brings the workflow closer to the [DFE-Digital/a2b-internal](https://github.com/DFE-Digital/a2b-internal/actions/workflows/build-and-push-image.yml) deployment pipeline by splitting the steps into separate jobs to make it easier to view the progress at-a-glance. 
It will also add the `latest` tag back onto the Docker image tags that get pushed to Azure Container Registry.
> Split workflow tasks apart into steps to improve readibility

- end-to-end-tests/cypress/e2e/Performance/preview and download template.cy.js
This test always fails the first time it runs after a deployment.
> upping timeout for test which always fails after a deployment

- end-to-end-tests/cypress/e2e/Performance/preview and download template.cy.js
Atm this performance was failing intermittently. Looking into the code it seems we were repeating some of the time logging. Also in the test case we don't need afterEach function as there is only one  test and the assertion we were checking in this function could also be done with in the test case
It has decreased the timeTaken value
> Fix performance test

- end-to-end-tests/package.json
Reverting this as it's causing issues in github workflow for end-to-end-tests. On local it works fine. SO the suggestion is to make the changes  for eslint and git hook in your local so that esLint run every time we commit 
P.S: esLint anyway is running when we merge the PR even if we don't create git hook here explicitly.
Reverts DFE-Digital/prepare-academy-transfers#512
> Revert "Another try to fix husky install issue"

- terraform.gpaas-azure-migration/README.md
- terraform.gpaas-azure-migration/container-apps-hosting.tf
- terraform.gpaas-azure-migration/data.tf
- terraform.gpaas-azure-migration/key-vault-tfvars-secrets.tf
- terraform.gpaas-azure-migration/locals.tf
- terraform.gpaas-azure-migration/variables.tf
What is the change?
Instead of defining all of the terraform for deploying a Key Vault, I have switched to using a terraform module which shifts a lot of the configurable options upstream and reduces the complexity of the terraform code in this repo.
Why do we need the change?
Allows for centralised updates for the Key Vault resource and reduces complexity of the terraform in this repo.
What is the impact?
Applying this terraform change will destroy the existing tfvars Key Vault and recreate it. This has no impact on the running services within Azure and is considered safe/low impact.
> Modularise Terraform Vars Key Vault

- terraform.gpaas-azure-migration/README.md
- terraform.gpaas-azure-migration/container-apps-hosting.tf
- terraform.gpaas-azure-migration/locals.tf
- terraform.gpaas-azure-migration/variables.tf
Adding NS records to your primary DNS Zone allows you to delegate records for subdomains into their own individual Zones instead of managing all records in your primary Zone.
> Added NS record option for delegating subdomains

- end-to-end-tests/cypress/e2e/benefits-and-risks/equalities-impact-assessment.cy.js
Atm one of the transfers test is failing due to data issue, the project does not exist anymore in the dev/staging env. . As a quick fix updating the project id.
> Cypress fix: Update project id

- Dfe.PrepareTransfers.Redirector/Dockerfile
The line is not required because the base image already exposes a port. GPaaS doesn't work with this line in (not sure why)
> Removing expose line which GPaaS doesn't like.

- .github/workflows/security-tests.yml
- end-to-end-tests/docker-compose.yml
Fixes configuration in the security tests workflow to allow the report to be uploaded to Azure Blob Storage for later viewing. Reports will always upload, regardless of test failures, as long as the action is not cancelled.
Files will be uploaded to a [container](https://portal.azure.com/#@platform.education.gov.uk/resource/subscriptions/1d692707-6019-4f8c-b337-ec8cad61f998/resourceGroups/s184d01-rsd-owasp-reports/providers/Microsoft.Storage/storageAccounts/s184d01rsdowaspreports/storagebrowser) on Azure under the directory `<project>/<git-hash>/ZAP-Report.html`.
> **Note**
> To read them you will need read access to Azure CIP.
Makes use of a Service Principal account to authenticate to Azure
**Notes**
The following need to be completed before this PR can be merged:
> Update security test workflow to upload report to blob storage

- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
* Allows specifying the Front Door CDN forwarding protocol
* Allows adding a list of IP addresses allowed to access the Container App
> Bump container apps hosting module to v0.19.1

- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
This is useful when the backend origin is only accepting http traffic
> Option to override CDN Health Probe protocol to use Http

- .github/workflows/continuous-integration-javascript.yml
- end-to-end-tests/cypress/.eslintrc.json
- end-to-end-tests/cypress/e2e/cookie-policy/cookies-policy.cy.js
Adds a workflow for Cypress linting when changes are made to it in a PR (shouldn't run if no changes are present in the `end-to-end-tests` directory)
Will fail the job if any of the configured rules return an error.
> Adds Cypress linting workflow for PRs with Cypress changes

- Dfe.PrepareTransfers.Data.TRAMS.Tests/Mappers/Request/InternalProjectToUpdateMapperTests.cs
- Dfe.PrepareTransfers.Data.TRAMS/Mappers/Request/InternalProjectToUpdateMapper.cs
- Dfe.PrepareTransfers.Web.Tests/PagesTests/Projects/TransferDates/AdvisoryBoardTests.cs
- Dfe.PrepareTransfers.Web.Tests/PagesTests/Projects/TransferDates/TargetTests.cs
- Dfe.PrepareTransfers.Web/Pages/Projects/TransferDates/AdvisoryBoard.cshtml.cs
- Dfe.PrepareTransfers.Web/Pages/Projects/TransferDates/Target.cshtml.cs
Moved the fix for transfer dates to the request mapping layer, outgoing dates are now universal datetime to avoid deserialization issues. Probably need to standardize these in the API in the JSON settings going forward.
> Transfer date fixes

- end-to-end-tests/cypress.config.js
Adds a User-Agent header for Cypress tests to mitigate issues with Azure thinking the traffic is from bots
> Add Cypress User-Agent header to config

- terraform/.terraform.lock.hcl
- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
Using a Managed Identity to pull images from Azure Container Registry is more preferable than using admin access keys.
This change will allow us to disable the 'admin' credentials for the Container registry.
Closes #636
> Deploy user assigned managed identity

- Dfe.PrepareTransfers.Web/Pages/Projects/Index.cshtml
Transfers:
- Add status tag to the right of the caption
- Add 'Route: Transfer' under the project name
- Change 'Create a project template' to 'Prepare a project document'
- Change 'By completing the following sections, you can create a project template...' to 'Complete the following sections to create  a project document...'
- Remove 'Rationale' and 'Benefits and risks' links from Transfer details
- Add section 'Give a case for this transfer' to include the 'Rationale' and 'Benefits and risks' links
- Add inset text component under 'School data' with text 'This information will be added to your project document automatically'
- Change list of schools to match how we have performance data on the conversions page
- Change heading 'Preview or generate project template' to 'Create your …
> update UI to be more consistent with conversions

- Dfe.PrepareTransfers.Web.Tests/ModelTests/ProjectListTests/ProjectListFiltersTests.cs
- Dfe.PrepareTransfers.Web.Tests/PagesTests/Home/IndexTests.cs
- Dfe.PrepareTransfers.Web.Tests/UtilsTests/TypeSpaceExtensionsTests.cs
- Dfe.PrepareTransfers.Web/Models/ProjectList/ProjectListFilters.cs
- Dfe.PrepareTransfers.Web/Pages/Home/Index.cshtml
- Dfe.PrepareTransfers.Web/Pages/Home/Index.cshtml.cs
- Dfe.PrepareTransfers.Web/Pages/Shared/_ProjectListFilters.cshtml
- Dfe.PrepareTransfers.Web/Utils/TypeSpaceExtensions.cs
[156379](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_sprints/taskboard/Manage%20Academy%20Projects/Academies-and-Free-Schools-SIP/Academisation%20Team/Sprint%204-%20Q4?workitem=156379)
This is a refactor only. It applies to the filtering on the transfers list page.
- I have move the filter button/panel html into it's own code space
- I have created a new filter model and moved the title filter into that model
This is now more consistent with conversions and will make handling/maintaining the filter(s) and query parameter(s) much easier when we get to it.
> move filter into separate model

- Dfe.PrepareTransfers.Data.TRAMS/AcademyTransfersAdvisoryBoardDecisionRepository.cs
- Dfe.PrepareTransfers.Data.TRAMS/Mappers/Response/AcademisationProjectMapper.cs
- Dfe.PrepareTransfers.Data.TRAMS/Models/AcademisationProject.cs
- Dfe.PrepareTransfers.Data/Models/Project.cs
- Dfe.PrepareTransfers.Web/Pages/TaskList/Decision/Models/DecisionBaseModel.cs
- Dfe.PrepareTransfers.Web/Pages/TaskList/Decision/RecordADecision.cshtml.cs
- Dfe.PrepareTransfers.Web/Pages/TaskList/Decision/Summary.cshtml.cs
Move from urn to the project id on the advisory board decision create. So historical transfer projects have the correct relationship between project and decision
> Fixes to use project id rather than urn on the transfer project advisory board decision

- .github/workflows/build-and-push-image.yml
* Using a centralised deployment workflow allows us to align the release process with other sibling services within RSD
> Use shared deployment workflow

- .github/workflows/build-and-push-image.yml
* This version change now publishes docker images to GitHub Container Registry, and imports them into Azure Container Registry instead of pushing directly to Azure.
> Update deployment workflow to use v2

- .github/workflows/build-and-push-image.yml
- .github/workflows/cypress.yml
Pulls out the Cypress tests into their own reusable workflow independent of the deploy workflow.
Cypress workflow can now either be triggered manually for dev/staging, or is called after a successful deployment.
> Reusable Cypress workflow

- Dfe.PrepareTransfers.Web/Startup.cs
Set a custom User-Agent HTTP Header so that traffic can be segmented when running reports against the downstream APIs
> Set HTTP user agent header
