- TRAMS-API/API.csproj
- TRAMS-API/API.xml
- TRAMS-API/Controllers/TrustsController.cs
- TRAMS-API/Models/Response/GetTrustsModel.cs
- TRAMS-API/Startup.cs
- TRAMS-API/appsettings.json
Add Swagger Generation and document Trusts controller
> Add Swagger Generation and document Trusts controller

- API.Tests/RepositoriesTests/TrustsRepositoryTests.cs
- TRAMS-API/API.xml
- TRAMS-API/HttpHelpers/IODataSanitizer.cs
- TRAMS-API/HttpHelpers/ODataSanitizer.cs
- TRAMS-API/Repositories/TrustsRepository.cs
- TRAMS-API/Startup.cs
Sanitizes OData search parameters
> PR: Sanitize OData search query

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Frontend.csproj
- Frontend/Helpers/Session.cs
- Frontend/Startup.cs
- Frontend/Views/Transfers/CheckYourAnswers.cshtml
- Frontend/Views/Transfers/CheckYourAnswers.cshtml.cs
- Frontend/Views/Transfers/IncomingTrust.cshtml
- Frontend/Views/Transfers/IncomingTrustDetails.cshtml
- Frontend/Views/Transfers/IncomingTrustIdentified.cshtml
- Frontend/Views/Transfers/ProjectFeatures.cshtml
- Frontend/Views/Transfers/ProjectFeatures.cshtml.cs
- Frontend/Views/Transfers/SearchIncomingTrust.cshtml
- Frontend/Views/Transfers/SubmitProject.cshtml
- Frontend/Views/Transfers/SubmitProject.cshtml.cs
- Frontend/Views/_ViewStart.cshtml
- Frontend/appsettings.Development.json
Part of the ongoing Rails rewrite. Covers the journey up to submitting a project to TRAMS
- Add ability to select incoming trust if identified
- Add Redis for session storage
- Display check your answers page
- Submit a project to TRAMS
> Finalise project creation

- Frontend/Controllers/HomeController.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Startup.cs
- Frontend/Views/Home/Index.cshtml
- Frontend/Views/Home/Login.cshtml
- Frontend/appsettings.Development.json
Part of the rewrite of the academy transfers rails frontend
- Adds a link to create a new transfer from the home page
- Puts cookie-based authentication around the service
- Uses environment variable based username/password for the authentication
> Home page and login

- API.Tests/ControllersTests/AcademiesControllerTests.cs
- API.Tests/ControllersTests/ProjectsControllerTests.cs
- API.Tests/ControllersTests/TrustsControllerTests.cs
- API.Tests/RepositoriesTests/AcademiesRepositoryTests.cs
- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- TRAMS-API/Controllers/AcademiesController.cs
- TRAMS-API/Controllers/TrustsController.cs
- TRAMS-API/Repositories/AcademiesRepository.cs
- TRAMS-API/Repositories/Interfaces/IAcademiesRepository.cs
In the future, we plan to change our data source from the TRAMS Dynamics API to a new API developed by the TRAMS API. To prepare for this, we want to move all the Dynamics-related mapping into the repository objects so they can be swapped out in the future.
- Push Mapping into Academies Reporitory
- Update references to Academies repository
> Refactor academies repo

- Frontend/Views/Transfers/CheckYourAnswers.cshtml
We want users to be able to check their answers before creating an academy transfers project
- Update the copy on the check your answers page
> Update the copy on the check your answers page

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Views/Transfers/CheckYourAnswers.cshtml
- Frontend/Views/Transfers/IncomingTrust.cshtml
- Frontend/Views/Transfers/IncomingTrustDetails.cshtml
- Frontend/Views/Transfers/OutgoingTrustAcademies.cshtml
- Frontend/Views/Transfers/SearchIncomingTrust.cshtml
To meet the designs & guidelines in the GOV.UK Design system, we want to allow our users to change their answers on reviewing them, as well as navigate correctly using the back links
- Add change link to outgoing academies
- Add incoming trust change links
> Change links for academies and incoming trust

- Frontend/Controllers/HomeController.cs
- Frontend/Views/Home/Index.cshtml
- Frontend/Views/Home/Index.cshtml.cs
- Frontend/wwwroot/package.json
- Frontend/wwwroot/src/css/site.scss
In the future we'll need to create a dashboard view of the currently existing academy transfers projects. Due to the limitations of the Dynamics API, most of this information is currently placeholder
- Add the initial HTML for the dashboard
- Populate it with any existing available information
> Add dashboard with placeholder text

- Data.Mock/MockAcademyRepository.cs
- Data/Models/Academy.cs
- Data/Models/PupilNumbers.cs
- Frontend.Tests/ControllerTests/Projects/PupilNumbersControllerTests.cs
- Frontend/Controllers/Projects/AcademyPerformanceController.cs
- Frontend/Controllers/Projects/PupilNumbersController.cs
- Frontend/Models/AcademyPerformanceViewModel.cs
- Frontend/Models/PupilNumbersViewModel.cs
- Frontend/Views/Project/Index.cshtml
- Frontend/Views/PupilNumbers/Index.cshtml
- Frontend/Views/Shared/_Layout.cshtml
Adding in the reference pages with placeholder information in preparation for integration with the new TRAMS API 
- Add pupil number data
- Create pupil numbers page
> Add pupil numbers page

- Data.Mock/MockAcademyRepository.cs
- Data/Models/Academy.cs
- Data/Models/LatestOfstedJudgement.cs
- Frontend.Tests/ControllerTests/Projects/LatestOfstedJudgementControllerTests.cs
- Frontend.Tests/Frontend.Tests.csproj
- Frontend/Controllers/Projects/LatestOfstedJudgementController.cs
- Frontend/Models/LatestOfstedJudgementViewModel.cs
- Frontend/Views/LatestOfstedJudgement/Index.cshtml
- Frontend/Views/Project/Index.cshtml
As part of the preparation for our integration with future APIs, creates a page with placeholder data
- Add latest ofsted judgement data
- Add latest ofsted judgement page
> Add latest ofsted judgement page

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Startup.cs
- Frontend/Views/Transfers/SearchIncomingTrust.cshtml
- Frontend/Views/Transfers/TrustSearch.cshtml
- Frontend/Views/Transfers/TrustSearch.cshtml.cs
- TRAMS-API/Wrappers/DynamicsTrustsWrapper.cs
Part of the migration away from dynamics to the new TRAMS API
- Remove TRN from trust search page as this isn't provided by the TRAMS API
- Migrate away from dynamics trust search to trams trust search
> Migrate trust searching

- Data.TRAMS/Mappers/Response/TramsTrustMapper.cs
- Data/Models/Trust.cs
- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Views/Transfers/CheckYourAnswers.cshtml
- Frontend/Views/Transfers/CheckYourAnswers.cshtml.cs
- Frontend/Views/Transfers/IncomingTrustDetails.cshtml
- Frontend/Views/Transfers/OutgoingTrustDetails.cshtml
- Frontend/Views/Transfers/OutgoingTrustDetails.cshtml.cs
- TRAMS-API/Wrappers/DynamicsTrustsWrapper.cs
Part of the migration away from dynamics to the new API
- Migrate trust details pages to new interface
- Migrate check your answers from get trust by id
> Migrate get trust by ID

- Data.TRAMS/TramsProjectsRepository.cs
- Data/IProjects.cs
- Data/Models/ProjectSearchResult.cs
- Frontend/Controllers/HomeController.cs
- Frontend/Views/Home/Index.cshtml
- Frontend/Views/Home/Index.cshtml.cs
- TRAMS-API/Wrappers/DynamicsProjectWrapper.cs
As part of the ongoing API migration work
Migrate Home controller to IProjects
> Migrate home controller to new interface

- Frontend.Tests/ControllerTests/HeadteacherBoardControllerTests.cs
- Frontend/Controllers/HeadteacherBoardController.cs
- Frontend/Services/CreateHtbDocument.cs
- Frontend/Services/Interfaces/ICreateHtbDocument.cs
As part of the ongoing work to migrate to the new APIs
- Migrate create HTB document to the new API interfaces
> Migrate create htb document

- Frontend.Tests/ControllerTests/Projects/TransferDatesControllerTests.cs
- Frontend.Tests/ModelTests/TransferDatesViewModelTests.cs
- Frontend/Controllers/Projects/TransferDatesController.cs
- Frontend/Helpers/DateTimeProvider.cs
- Frontend/Helpers/DatesHelper.cs
- Frontend/Helpers/IDateTimeProvider.cs
- Frontend/Models/TransferDatesViewModel.cs
- Frontend/Startup.cs
- Frontend/Views/TransferDates/HtbDate.cshtml
- Frontend/Views/TransferDates/Index.cshtml
The HTB Date is able to be selected by the user - this has to be a selection of the first _working_ day of each month.
- Add HTB Date generation to view model
- Add the ability to select the HTB Date
> Add HTB Date page

- Data.Mock/MockProjectRepository.cs
- Data/Models/Project.cs
- Frontend.Tests/ControllerTests/Projects/BenefitsControllerTests.cs
- Frontend.Tests/Helpers/DatesHelperTests.cs
- Frontend.Tests/ModelTests/BenefitsViewModelTests.cs
- Frontend/Controllers/Projects/BenefitsController.cs
- Frontend/Helpers/DatesHelper.cs
- Frontend/Helpers/EnumHelpers.cs
- Frontend/Models/BenefitsViewModel.cs
- Frontend/Views/Benefits/Index.cshtml
- Frontend/Views/Benefits/IntendedBenefits.cshtml
- Frontend/Views/Benefits/OtherFactors.cshtml
- Frontend/Views/Project/Index.cshtml
Adding in the ability for users to create the benefits and other factors in the project
- Add project data models
- Add additional edge case for htb date generation
- Add Intended transfer benefits page
- Allow users to save other factors
- Display selected other factors on the summary page
- Add mock data for transfer benefits
- Update summary views with links and titles
> Benefits and other factors

- Frontend.Tests/ControllerTests/Projects/RationaleControllerTests.cs
- Frontend/Controllers/Projects/RationaleController.cs
- Frontend/Models/RationaleViewModel.cs
- Frontend/Views/Project/Index.cshtml
- Frontend/Views/Rationale/Index.cshtml
- Frontend/Views/Rationale/Project.cshtml
- Frontend/Views/Rationale/TrustOrSponsor.cshtml
- Frontend/wwwroot/src/css/site.scss
To allow our users to input the rationales for the project & trust choices
- Add rationale to project model
- Add rationale pages
> Add rationale pages

- Frontend/Views/AcademyPerformance/Index.cshtml
- Frontend/Views/Benefits/IntendedBenefits.cshtml
- Frontend/Views/Benefits/OtherFactors.cshtml
- Frontend/Views/Features/Type.cshtml
- Frontend/Views/HeadteacherBoard/Download.cshtml
- Frontend/Views/Home/Login.cshtml
- Frontend/Views/Transfers/CheckYourAnswers.cshtml
- Frontend/Views/Transfers/IncomingTrust.cshtml
- Frontend/Views/Transfers/IncomingTrustDetails.cshtml
- Frontend/Views/Transfers/IncomingTrustIdentified.cshtml
- Frontend/Views/Transfers/OutgoingTrustAcademies.cshtml
- Frontend/Views/Transfers/OutgoingTrustDetails.cshtml
- Frontend/Views/Transfers/ProjectFeatures.cshtml
- Frontend/Views/Transfers/SearchIncomingTrust.cshtml
- Frontend/Views/Transfers/TrustSearch.cshtml
Update page titles
Some page titles were showing as 'title', updated these to show relevant title
> Added page titles where required

- Frontend/Views/Benefits/IntendedBenefits.cshtml
- Frontend/Views/Benefits/OtherFactors.cshtml
- Frontend/Views/Rationale/Project.cshtml
- Frontend/Views/Rationale/TrustOrSponsor.cshtml
Some of the pages were missing back links to the summary pages
- Add back link to benefits data entry pages
- Add back link to rationale data entry pages
> Add missing back links to pages

- Frontend/Views/Transfers/CheckYourAnswers.cshtml
- Frontend/Views/Transfers/OutgoingTrustAcademies.cshtml
- Frontend/Views/Transfers/OutgoingTrustDetails.cshtml
- Frontend/Views/Transfers/TrustName.cshtml
- Frontend/Views/Transfers/TrustSearch.cshtml
The prototype has updated the transfer project creation flow in order to make it more inline with the govuk design system.
This PR is the first one to start bringing our service inline with the prototype
- Update check your answers page to bring it inline with the prototype
- Update add outgoing trust search
- Update outgoing trust search list
- Update outgoing trust details page
- Update outgoing trust academies page
> Update creation pages (part one)

- Data/Models/ProjectStatuses.cs
- Frontend.Tests/ControllerTests/ProjectControllerTests.cs
- Frontend.Tests/HelpersTests/TagHelperTests/ProjectStatusTagHelperTests.cs
- Frontend.Tests/ModelTests/ProjectTaskListViewModelTests.cs
- Frontend/Controllers/ProjectController.cs
- Frontend/Helpers/TagHelpers/ProjectStatusTagHelper.cs
- Frontend/Models/ProjectTaskListViewModel.cs
- Frontend/Views/Project/Index.cshtml
- Frontend/Views/_ViewImports.cshtml
Update the status of each section when it is completed on the create HTB template page
- Update Features of a transfer status (for in progress and complete)
- Update Set transfer dates status (for in progress and complete)
- Update Benefits status (for in progress and complete)
- Update Rationale status (for in progress and complete)
> Project status updates

- Data.Mock/MockAcademyRepository.cs
- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Views/Transfers/IncomingTrust.cshtml
Update the "add incoming trust" page to show updated content
- Add outgoing academy to the title
- Update hint text to replace TRN with UKPRN
- Update button text to replace Submit with Search
- Update title size to replace l with xl
> Update add-incoming-trust page

- Frontend/Views/Transfers/IncomingTrust.cshtml
Add outgoing academy name to the add-incoming-trust page title
Add outgoing academy name to the add-incoming-trust page title
> Add outgoing academy name to page title

- Data.Mock/MockProjectRepository.cs
- Data/Models/Project.cs
- Data/Models/ProjectSearchResult.cs
- Data/Models/Projects/TransferringAcademies.cs
- Frontend/Views/AcademyPerformance/Index.cshtml
- Frontend/Views/Benefits/Index.cshtml
- Frontend/Views/Features/Index.cshtml
- Frontend/Views/Home/Index.cshtml
- Frontend/Views/LatestOfstedJudgement/Index.cshtml
- Frontend/Views/Project/Index.cshtml
- Frontend/Views/PupilNumbers/Index.cshtml
- Frontend/Views/Rationale/Index.cshtml
- Frontend/Views/TransferDates/Index.cshtml
- Frontend/wwwroot/src/css/_application-card.scss
- Frontend/wwwroot/src/css/site.scss
Part of the Academy conversion alignment work
- Update homepage
- Refer to outgoing academy URN instead of project URN
- Update task list heading content
- Update mock data
> Update Home page and other content

- Frontend/Views/Project/Index.cshtml
Our task list links were missing the `govuk-link` class
- Add `govuk-link` to task list links
> Apply GOV.UK link styles to task list links

- Frontend.Tests/ControllerTests/HeadteacherBoardControllerTests.cs
- Frontend/Controllers/HeadteacherBoardController.cs
- Frontend/Views/HeadteacherBoard/Download.cshtml
- Frontend/wwwroot/src/css/_attachment.scss
- Frontend/wwwroot/src/css/site.scss
Updating content in line with Academy Conversions
- Update HTB Document Download page
> Update HTB Document download page

- Data/Models/Project.cs
- Frontend.Tests/ControllerTests/Projects/AcademyPerformanceControllerTests.cs
- Frontend.Tests/ControllerTests/Projects/LatestOfstedJudgementControllerTests.cs
- Frontend.Tests/ControllerTests/Projects/PupilNumbersControllerTests.cs
- Frontend/Controllers/Projects/AcademyPerformanceController.cs
- Frontend/Controllers/Projects/LatestOfstedJudgementController.cs
- Frontend/Controllers/Projects/PupilNumbersController.cs
- Frontend/Models/AcademyPerformanceViewModel.cs
- Frontend/Models/Forms/AdditionalInformationViewModel.cs
- Frontend/Models/LatestOfstedJudgementViewModel.cs
- Frontend/Models/PupilNumbersViewModel.cs
- Frontend/Views/AcademyPerformance/Index.cshtml
- Frontend/Views/LatestOfstedJudgement/Index.cshtml
- Frontend/Views/PupilNumbers/Index.cshtml
- Frontend/Views/Shared/_AdditionalInformation.cshtml
Add additional information to Reference pages
Add additional information to academy performance page
Add additional information to pupil numbers page
Add additional information to Ofsted page
> Add additional information to Academy Performance page

- Frontend/Views/AcademyPerformance/Index.cshtml
- Frontend/Views/Benefits/Index.cshtml
- Frontend/Views/Features/Index.cshtml
- Frontend/Views/Home/Index.cshtml
- Frontend/Views/LatestOfstedJudgement/Index.cshtml
- Frontend/Views/PupilNumbers/Index.cshtml
- Frontend/Views/Rationale/Index.cshtml
- Frontend/Views/TransferDates/Index.cshtml
Updating content based on new designs
- Update homepage content and layout
- Remove content from mini summary pages
> Update content based on feedback

- Data.TRAMS.Tests/TramsAcademiesRepositoryTests.cs
- Data.TRAMS/TramsEstablishmentRepository.cs
- Frontend.Tests/ControllerTests/Projects/AcademyPerformanceControllerTests.cs
- Frontend.Tests/ServicesTests/GetInformationForProjectTests.cs
- Frontend/Controllers/Projects/AcademyPerformanceController.cs
- Frontend/Services/GetInformationForProject.cs
- Frontend/Services/Responses/GetInformationForProjectResponse.cs
- Frontend/Services/Responses/ServiceResponseError.cs
- Frontend/Views/Shared/ErrorPage.cshtml
We need to handle errors from the API otherwise our service will present errors to the user
- Handle errors in academy repository
- Handle academy repository errors in GetInformationForProject
- Handle errors for academy performance
> Handle errors from academy repository

- Data.TRAMS.Tests/Mappers/Response/TramsSearchResultMapperTests.cs
- Data.TRAMS.Tests/TestFixtures/TrustSearchResults.cs
- Data.TRAMS.Tests/TramsTrustsRepositoryTests.cs
- Data.TRAMS/Mappers/Response/TramsSearchResultMapper.cs
- Data.TRAMS/Models/TramsTrustSearchResult.cs
- Data.TRAMS/TramsTrustsRepository.cs
- Frontend/Views/Transfers/IncomingTrust.cshtml
- Frontend/Views/Transfers/TrustName.cshtml
The TRAMS API team have fixed the timeouts, and as such we can use the trust search endpoint correctly
- Remove workaround step
- Update params in search to match actual naming
> Reimplement trust search

- Frontend/Views/TransferDates/HtbDate.cshtml
Content updates for the HTB Date entry page
- Add hint text
- Fix titles
> Update HTB Date entry content

- Data.TRAMS.Tests/TramsProjectsRepositoryTests.cs
- Data.TRAMS/TramsProjectsRepository.cs
Add http error handling to TRAMS Project repository
Add error handling for http errors when making calls to projects repo
> Add http error handling to TRAMS Project repository

- Frontend.Tests/ControllerTests/Projects/BenefitsControllerTests.cs
- Frontend/Controllers/Projects/BenefitsController.cs
Add Error handling to Benefits controller
Add Error handling to Benefits controller
> Add Error handling to Benefits controller

- Frontend.Tests/ControllerTests/Projects/FeaturesControllerTests.cs
- Frontend/Controllers/Projects/FeaturesController.cs
Add error handling to features controller
Add error handling to features controller
> Add error handling to features controller

- Frontend.Tests/ControllerTests/Projects/LatestOfstedJudgementControllerTests.cs
- Frontend/Controllers/Projects/LatestOfstedJudgementController.cs
Add error handling to LatestOfsted controller
Add error handling to LatestOfsted controller
> Add error handling to LatestOfsted controller

- Data.TRAMS.Tests/Helpers/HttpClientTestHelpers.cs
- Data.TRAMS.Tests/TramsTrustsRepositoryTests.cs
- Data.TRAMS/TramsTrustsRepository.cs
- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
We need to support not crashing if the TRAMS API Encounters an error
- Handle errors in trust repository
- Handle trust repository errors in transfer creation
> Trust repository error handling

- Frontend/Controllers/HomeController.cs
- Frontend/Frontend.csproj
- Frontend/Program.cs
Investigation into structured logging
Add serilog for outputting structured logs
> Add Serilog for structured logging

- Frontend.Tests/ControllerTests/Projects/PupilNumbersControllerTests.cs
- Frontend/Controllers/Projects/PupilNumbersController.cs
Add Error handling to Pupil Numbers controller
Add Error handling to Pupil Numbers controller
> Add Error handling to Pupil Numbers controller

- Frontend.Tests/ControllerTests/ProjectControllerTests.cs
- Frontend/Controllers/ProjectController.cs
Add error handling to project controller
Add error handling to project controller
> Add error handling to project controller

- Frontend.Tests/ControllerTests/Projects/LatestOfstedJudgementControllerTests.cs
- Frontend.Tests/ControllerTests/Projects/PupilNumbersControllerTests.cs
- Frontend.Tests/ControllerTests/Projects/RationaleControllerTests.cs
- Frontend/Controllers/Projects/RationaleController.cs
Add error handling to rationale controller
Add error handling to rationale controller
> Add error handling to rationale controller

- Frontend.Tests/ControllerTests/Projects/TransferDatesControllerTests.cs
- Frontend/Controllers/Projects/TransferDatesController.cs
Add error handling to transfer date controller
Add error handling to transfer date controller
> Add error handling to transfer date controller

- Frontend/Views/Project/Index.cshtml
Remove additional item from task list
- Remove duplicate rationale from task list
> Remove additional rationale

- Frontend.Tests/ControllerTests/HeadteacherBoardControllerTests.cs
- Frontend.Tests/ControllerTests/HomeControllerTests.cs
- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend.Tests/ServicesTests/CreateHtbDocumentTests.cs
- Frontend/Controllers/HeadteacherBoardController.cs
- Frontend/Controllers/HomeController.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Services/CreateHtbDocument.cs
- Frontend/Services/Interfaces/ICreateHtbDocument.cs
- Frontend/Services/Responses/CreateHtbDocumentResponse.cs
Add error handling to HTB, Home and Transfers controllers
Add error handling to HTB controller
Add error handling to Home controller
Add error handling to Transfers controller (for project repo actions)
> Add error handling to HTB controller

- Data.Mock/MockAcademyRepository.cs
- Data.TRAMS.Tests/Mappers/Response/TramsEstablishmentMapperTests.cs
- Data.TRAMS/Mappers/Response/TramsEstablishmentMapper.cs
- Data/Models/Academies/LatestOfstedJudgement.cs
- Frontend/Views/HeadteacherBoard/Preview.cshtml
- Frontend/Views/LatestOfstedJudgement/Index.cshtml
Update ofsted page
Remove unused fields
Add link to Ofsted Report
Adjust styling
> Update Ofsted judgement page

- Frontend/Views/LatestOfstedJudgement/Index.cshtml
Add link styling and (opens in new tab) text to link
Add govuk-link to ofsted report link
Add (opens in new tab) to ofsted report link
> Add link styling and (opens in new tab) text to link

- DocumentGeneration.Tests/DocumentBuilderTests.cs
- DocumentGeneration/Builders/FooterBuilder.cs
- DocumentGeneration/Builders/HeaderBuilder.cs
- DocumentGeneration/DocumentBuilder.cs
- DocumentGeneration/Interfaces/Parents/ITableParent.cs
- Frontend/Services/CreateHtbDocument.cs
The HTB document is undergoing design changes, this brings it closer in line to the new design for a proof of concept
- Support quick adding tables
- Update HTB document template to reflect new design
> Update HTB Document layout

- Frontend/Startup.cs
Add validation of anti forgery token sent with HTTP POST requests to prevent XSRF/CSRF attacks
Add validation of anti forgery token sent with HTTP POST requests to prevent XSRF/CSRF attacks
> Add AutoValidateAntiforgeryTokenAttribute to all controllers

- Frontend/Views/Shared/_Layout.cshtml
- Frontend/appsettings.Development.json
Add beta banner to layout
Add beta banner to layout
Add temp email address to appsettings
> Add beta banner to layout

- Data/Models/Project.cs
- Frontend.Tests/PagesTests/KeyStage2PerformanceTests.cs
- Frontend/Pages/KeyStage2Performance.cshtml
- Frontend/Pages/KeyStage2Performance.cshtml.cs
- Frontend/Pages/_ViewImports.cshtml
- Frontend/Startup.cs
- Frontend/Views/Project/Index.cshtml
Add key stage 2 performance page
Set up the project to use razor pages
Add key stage 2 performance page with placeholders for data
> Add key stage 2 performance page

- Data.TRAMS.Tests/Mappers/Response/TramsEducationPerformanceMapperTests.cs
- Data.TRAMS.Tests/TestFixtures/EducationPerformance.cs
- Data.TRAMS.Tests/TramsEducationPerformanceRepositoryTests.cs
- Data.TRAMS/Mappers/Response/TramsEducationPerformanceMapper.cs
- Data.TRAMS/Models/EducationPerformance/DisadvantagedPupilsResponse.cs
- Data.TRAMS/Models/EducationPerformance/KeyStage2.cs
- Data.TRAMS/Models/EducationPerformance/TramsEducationPerformance.cs
- Data.TRAMS/TramsEducationPerformanceRepository.cs
- Data/IEducationPerformance.cs
- Data/Models/KeyStagePerformance/DisadvantagedPupilsResult.cs
- Data/Models/KeyStagePerformance/EducationPerformance.cs
- Data/Models/KeyStagePerformance/KeyStage2.cs
- Frontend.Tests/Helpers/RazorPageTestHelpers.cs
- Frontend.Tests/PagesTests/KeyStage2PerformanceTests.cs
- Frontend.Tests/ServicesTests/GetInformationForProjectTests.cs
- Frontend/ExtensionMethods/PageModelExtensions.cs
- Frontend/Models/ProjectTaskListViewModel.cs
- Frontend/Pages/KeyStage2Performance.cshtml
- Frontend/Pages/KeyStage2Performance.cshtml.cs
- Frontend/Services/GetInformationForProject.cs
- Frontend/Services/Responses/GetInformationForProjectResponse.cs
- Frontend/Startup.cs
Add integration with TRAMS api for key stage 2 performance page
Add TRAMS models and mappers to retrieve education performance data
Create education performance repository
Update to use razor page
> Add integration with TRAMS api for key stage 2 performance page

- Frontend.Tests/ControllerTests/ProjectControllerTests.cs
- Frontend/Controllers/ProjectController.cs
- Frontend/Pages/KeyStage2Performance.cshtml
- Frontend/Views/Project/Index.cshtml
Remove key stage 2 link from task list if no data exists
Remove key stage 2 link from task list if no data exists
> Remove key stage 2 link from task list if no data exists

- Data.TRAMS.Tests/Mappers/Request/InternalProjectToUpdateMapperTests.cs
- Data.TRAMS.Tests/Mappers/Response/TramsProjectMapperTests.cs
- Data.TRAMS/Mappers/Request/InternalProjectToUpdateMapper.cs
- Data.TRAMS/Mappers/Response/TramsProjectMapper.cs
- Data.TRAMS/Models/TramsProject.cs
- Data.TRAMS/Models/TramsProjectUpdate.cs
- Data/Models/Project.cs
- Frontend.Tests/ControllerTests/Projects/LatestOfstedJudgementControllerTests.cs
- Frontend/Controllers/Projects/LatestOfstedJudgementController.cs
Add additional information fields to internal and TRAMS models to integrate with TRAMS API
Add additional information fields to models
Add mapping
Add tests
> Add additional information fields

- Frontend.Tests/PagesTests/KeyStage2PerformanceTests.cs
- Frontend/Pages/KeyStage2Performance.cshtml
- Frontend/Pages/KeyStage2Performance.cshtml.cs
- Frontend/Views/Shared/_AdditionalInformation.cshtml
Add additional information to KS2 page
Add additional information to KS2 page
Add integration with TRAMS API for additional information
> Add additional information to KS2 page

- Frontend/Views/Home/Index.cshtml
We no longer need this information
- Remove LA from the project list
> Remove the local authority from the project dashboard

- Data.TRAMS.Tests/Mappers/Response/TramsEducationPerformanceMapperTests.cs
- Data.TRAMS.Tests/TestFixtures/EducationPerformance.cs
- Data.TRAMS/Mappers/Response/TramsEducationPerformanceMapper.cs
- Data.TRAMS/Models/EducationPerformance/KeyStage4.cs
- Data.TRAMS/Models/EducationPerformance/TramsEducationPerformance.cs
- Data/Models/KeyStagePerformance/EducationPerformance.cs
- Data/Models/KeyStagePerformance/KeyStage4.cs
Add integration with TRAMS API for KS4 data
Add ks4 models and mapping
> Add integration with TRAMS API for KS4 data

- Frontend.Tests/HelpersTests/PerformanceDataHelpersTests.cs
- Frontend.Tests/PagesTests/KeyStage4PerformanceTests.cs
- Frontend/Controllers/ProjectController.cs
- Frontend/Helpers/PerformanceDataHelpers.cs
- Frontend/Pages/KeyStage4Performance.cshtml
- Frontend/Pages/KeyStage4Performance.cshtml.cs
- Frontend/Views/Project/Index.cshtml
Add key stage 4 performance page
Add key stage 4 performance page
> Add key stage 4 performance page

- Frontend.Tests/ModelTests/ProjectTaskListViewModelTests.cs
- Frontend/Models/ProjectTaskListViewModel.cs
- Frontend/Views/Project/Index.cshtml
Update KS2 and KS4 has data checks
Move has data checks to the project task list view model
Add tests
> Update KS2 and KS4 has data checks

- .github/workflows/tf-plan.yml
- terraform/main.tf
- terraform/production.tfvars
- terraform/variables.tf
We're migrating our deploys to use terraform, this sets up the production environment
- Make docker image a variable
- Add production tf vars
- Uncomment/remove some of the tf plan workflow
> Add production terraform

- Frontend/Controllers/HomeController.cs
- Frontend/Views/Shared/_Layout.cshtml
- Frontend/wwwroot/src/css/site.scss
We need users to have the ability to sign out
- Add sign out button to layout in the header
> Add sign out button

- Frontend/Controllers/HomeController.cs
- Frontend/Views/Home/Login.cshtml
- Frontend/Views/Shared/_Notification.cshtml
So that users know their logout was successful
- Add notification partial for success notifications
- Display success notifcation on sign out
> Display success notification on sign out

- Frontend/Pages/TaskList/AcademyAndTrustInformation/AcademyAndTrustInformation.cshtml
- Frontend/Pages/TaskList/Benefits/Benefits.cshtml
- Frontend/Pages/TaskList/Features/Features.cshtml
- Frontend/Pages/TaskList/HtbDocument/KeyStage2PerformanceSummary.cshtml
- Frontend/Pages/TaskList/HtbDocument/KeyStage4PerformanceSummary.cshtml
- Frontend/Pages/TaskList/HtbDocument/KeyStage5PerformanceSummary.cshtml
- Frontend/Pages/TaskList/HtbDocument/LatestOfstedJudgement.cshtml
- Frontend/Pages/TaskList/HtbDocument/PupilNumbers.cshtml
- Frontend/Pages/TaskList/Rationale/Rationale.cshtml
- Frontend/Pages/TaskList/TransferDates/TransferDates.cshtml
- Frontend/Views/AcademyAndTrustInformation/Index.cshtml
- Frontend/Views/Benefits/Index.cshtml
- Frontend/Views/Features/Index.cshtml
- Frontend/Views/Rationale/Index.cshtml
- Frontend/Views/Shared/_AdditionalInformation.cshtml
- Frontend/Views/TransferDates/Index.cshtml
- Frontend/Views/Transfers/CheckYourAnswers.cshtml
Add space to change links hidden text
Add space to change links hidden text
> Add space to change links hidden text

- Data.TRAMS.Tests/Mappers/Response/TramsEstablishmentMapperTests.cs
- Data.TRAMS/Mappers/Response/TramsEstablishmentMapper.cs
- Helpers.Tests/PercentageHelperTests.cs
- Helpers/PercentageHelper.cs
Move percentage helper to separate helper class
Move percentage helper to separate helper class
> Move percentage helper to separate helper class

- Frontend.Tests/ServicesTests/GetHtbDocumentForProjectTests.cs
- Frontend.Tests/TestFixtures/GetInformationForProject.cs
- Frontend/Services/GetHtbDocumentForProject.cs
Fix FSM data on HTB document
The wrong FSM figure was being pulled in to HTB document, this fixes that
> Fix FSM data on HTB document

- Frontend.Tests/ServicesTests/GetHtbDocumentForProjectTests.cs
- Frontend/Pages/TaskList/AcademyAndTrustInformation/AcademyAndTrustInformation.cshtml
- Frontend/Services/GetHtbDocumentForProject.cs
- Frontend/Views/AcademyAndTrustInformation/Index.cshtml
Update trust name to title case
Update trust name to title case
> Update trust name to title case

- Frontend/Views/Shared/_AdditionalInformation.cshtml
Updating content based on feedback
- Update additional information title in line with feedback
> Update additional information text

- Frontend/Views/Home/Index.cshtml
Remove utility class from dashboard
Remove utility css class from dashboard
> Remove utility class from dashboard

- Frontend.Tests/HelpersTests/PerformanceDataHelpersTests.cs
- Frontend/Helpers/PerformanceDataHelpers.cs
Change disadvantaged to read disadvantaged pupils
Change disadvantaged to read disadvantaged pupils
> Change disadvantaged to read disadvantaged pupils

- Data.TRAMS.Tests/Mappers/Response/TramsEducationPerformanceMapperTests.cs
- Data.TRAMS.Tests/TestFixtures/EducationPerformance.cs
- Data.TRAMS/Mappers/Response/TramsEducationPerformanceMapper.cs
- Data.TRAMS/Models/EducationPerformance/KeyStage4.cs
- Data/Models/KeyStagePerformance/KeyStage4.cs
- Frontend/Pages/TaskList/KeyStage4Performance/KeyStage4PerformanceTables.cshtml
- Frontend/Services/CreateHtbDocument.cs
Add percentage of pupils entering Ebacc measure to KS4
Add percentage of pupils entering Ebacc measure to KS4
> Add percentage of pupils entering Ebacc measure to KS4

- Frontend.Tests/ControllerTests/Projects/TransferDatesControllerTests.cs
- Frontend/Controllers/Projects/TransferDatesController.cs
- Frontend/Views/TransferDates/HtbDate.cshtml
Error messages on dates needed a content update
- Update content for date error messages
> Update dates error message content

- Frontend/Controllers/HomeController.cs
- Frontend/Controllers/ProjectController.cs
- Frontend/Startup.cs
Some routes were allowing unauthenticated access
- Setup default authorization on pages and controller routes
> Automatically set up authentication on routes

- Frontend/Views/Shared/_Layout.cshtml
Add support email to footer
Add support email to footer
> Add support email to footer

- Frontend.Tests/ControllerTests/Projects/FeaturesControllerTests.cs
- Frontend.Tests/ControllerTests/Projects/TransferDatesControllerTests.cs
- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/Projects/BenefitsController.cs
- Frontend/Controllers/Projects/FeaturesController.cs
- Frontend/Controllers/Projects/RationaleController.cs
- Frontend/Controllers/Projects/TransferDatesController.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Views/AcademyAndTrustInformation/Index.cshtml
- Frontend/Views/AcademyAndTrustInformation/Recommendation.cshtml
- Frontend/Views/GeneralInformation/Index.cshtml
- Frontend/Views/Home/Index.cshtml
- Frontend/Views/Project/Index.cshtml
- Frontend/Views/Rationale/Project.cshtml
- Frontend/Views/Rationale/TrustOrSponsor.cshtml
- Frontend/Views/Shared/_FormFieldSummaryList.cshtml
- Frontend/Views/Shared/_Layout.cshtml
Various minor content updates
Minor content tweaks to wording
Remove Please from all error messages
Replace EMPTY tag with No data
> Content updates

- Frontend/Controllers/HeadteacherBoardController.cs
- Frontend/Pages/TaskList/HtbDocument/Preview.cshtml
- Frontend/Views/AcademyAndTrustInformation/Index.cshtml
- Frontend/Views/Benefits/Index.cshtml
- Frontend/Views/Features/Index.cshtml
- Frontend/Views/Home/Index.cshtml
- Frontend/Views/LatestOfstedJudgement/Index.cshtml
- Frontend/Views/Project/Index.cshtml
- Frontend/Views/Rationale/Index.cshtml
- Frontend/Views/Shared/_Layout.cshtml
- Frontend/Views/TransferDates/Index.cshtml
- Frontend/Views/Transfers/CheckYourAnswers.cshtml
- Frontend/Views/Transfers/OutgoingTrustDetails.cshtml
Accessibility buttons and content fixes
Update page title on home page to deal with null values
Change Htb template name to project template
Spelling corrections
Update buttons rendered as anchors to be buttons
> Accessibility buttons and content fixes

- Frontend/Startup.cs
Add basic health check end point for integration with status cake
Add basic health check end point for integration with status cake
> Add basic health check end point for integration with status cake

- Frontend/Pages/AccessibilityStatement.cshtml
- Frontend/Views/Shared/_Layout.cshtml
Add initial accessibility statement - note more work to do to confirm content
Add initial accessibility statement
> Add initial accessibility statement

- .github/workflows/end_to_end_tests.yml
- Frontend/Program.cs
- Frontend/Startup.cs
- Frontend/Views/Home/Login.cshtml
Provide fixes to some of the issues highlighted in the IT health check report
1. Add secure HTTP headers to all responses
2. Set autocomplete to off for password input element
3. Remove `server` HTTP header from all responses
> Health check fixes

- Frontend/Pages/TaskList/KeyStage2Performance/KeyStage2Performance.cshtml
- Frontend/Pages/TaskList/KeyStage4Performance/KeyStage4Performance.cshtml
- Frontend/Pages/TaskList/KeyStage5Performance/KeyStage5Performance.cshtml
- Frontend/Views/GeneralInformation/Index.cshtml
- Frontend/Views/LatestOfstedJudgement/Index.cshtml
- Frontend/Views/Project/Index.cshtml
- Frontend/Views/PupilNumbers/Index.cshtml
Update task list and reference page content
Update content on task list page
Update content on reference pages
> Update task list and reference page content

- Frontend/Views/Project/Index.cshtml
Small content change to text on task list page (features of a transfer to features of the transfer)
Small content change
Change `Features of a transfer` to `Features of the transfer` on task list page
Also test if code change triggers logit update of sink url
> Small content change to text on task list page (features of a transfer to features of the transfer)

- Frontend.Tests/ControllerTests/Projects/RationaleControllerTests.cs
- Frontend.Tests/HelpersTests/TagHelperTests/GdsValidationForTagHelperTests.cs
- Frontend.Tests/ValidatorTests/RationaleProjectValidatorTests.cs
- Frontend/Controllers/Projects/RationaleController.cs
- Frontend/Helpers/TagHelpers/GdsValidationForTagHelper.cs
- Frontend/Models/Rationale/RationaleCommonViewModel.cs
- Frontend/Models/Rationale/RationaleProjectViewModel.cs
- Frontend/Validators/Rationale/RationalProjectValidator.cs
- Frontend/Views/Rationale/Project.cshtml
- end-to-end-tests/cypress/integration/project-runthrough.spec.js
Update project rational validation
Add tag helper to render property validation
Remove project rational validation from controller
Add validator for project rationale
> Update project rational validation

- Data/Models/Projects/TransferAcademyAndTrustInformation.cs
- Frontend.Tests/ServicesTests/GetHtbDocumentForProjectTests.cs
- Frontend.Tests/TestFixtures/GetInformationForProject.cs
Remove Defer option from recommendation
Note manually updated all dev current records that are set with defer option to declined, there are non in production
Remove Defer option from recommendation
> Remove Defer option from recommendation

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend.Tests/ValidatorTests/Features/FeaturesInitiatedValidatorTests.cs
- Frontend.Tests/ValidatorTests/Features/FeaturesReasonValidatorTests.cs
- Frontend.Tests/ValidatorTests/Features/FeaturesTypeValidatorTests.cs
- Frontend.Tests/ValidatorTests/Transfers/IncomingTrustConfirmValidatorTests.cs
- Frontend.Tests/ValidatorTests/Transfers/IncomingTrustNameValidatorTests.cs
- Frontend.Tests/ValidatorTests/Transfers/IncomingTrustSearchValidatorTests.cs
- Frontend.Tests/ValidatorTests/Transfers/OutgoingTrustAcademiesValidatorTests.cs
- Frontend.Tests/ValidatorTests/Transfers/OutgoingTrustConfirmValidatorTests.cs
- Frontend.Tests/ValidatorTests/Transfers/OutgoingTrustNameValidatorTests.cs
- Frontend.Tests/ValidatorTests/Transfers/OutgoingTrustSearchValidatorTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Validators/Transfers/IncomingTrustConfirmValidator.cs
- Frontend/Validators/Transfers/IncomingTrustNameValidator.cs
- Frontend/Validators/Transfers/IncomingTrustSearchValidator.cs
- Frontend/Validators/Transfers/OutgoingTrustAcademiesValidator.cs
- Frontend/Validators/Transfers/OutgoingTrustConfirmValidator.cs
- Frontend/Validators/Transfers/OutgoingTrustNameValidator.cs
- Frontend/Validators/Transfers/OutgoingTrustSearchValidator.cs
- Frontend/Validators/Transfers/TrustSearchResultValidator.cs
- Frontend/Views/Features/Initiated.cshtml
- Frontend/Views/Features/Reason.cshtml
- Frontend/Views/Features/Type.cshtml
- Frontend/Views/Shared/_InlineRadioButtons.cshtml
- Frontend/Views/Shared/_RadioButtons.cshtml
- Frontend/Views/Transfers/OutgoingTrustAcademies.cshtml
Tech Debt - transfers validation
Move Validation out of controller to fluent validation
Fix bug from changing the radio button id's to allow clicking of the label
> Tech Debt - transfers validation

- Frontend.Tests/ControllerTests/Projects/TransferDatesControllerTests.cs
- Frontend.Tests/ModelTests/TransferDatesTests/DateViewModelTests.cs
- Frontend.Tests/ValidatorTests/TransferDates/DateValidatorTests.cs
- Frontend.Tests/ValidatorTests/TransferDates/FirstDiscussedDateValidatorTests.cs
- Frontend/Controllers/Projects/TransferDatesController.cs
- Frontend/Models/Forms/CommonViewModel.cs
- Frontend/Models/TransferDates/DateViewModel.cs
- Frontend/Models/TransferDates/FirstDiscussedViewModel.cs
- Frontend/Validators/TransferDates/DateValidator.cs
- Frontend/Validators/TransferDates/FirstDiscussedDateValidator.cs
- Frontend/Views/TransferDates/FirstDiscussed.cshtml
- Frontend/Views/TransferDates/HtbDate.cshtml
- Frontend/Views/TransferDates/TargetDate.cshtml
- end-to-end-tests/cypress/support/commands.js
Improve date validation on first discussed page
Remove validation from controller
Add date validator
Add view model
> Improve date validation on first discussed page

- Frontend/Pages/AccessibilityStatement.cshtml
- Frontend/Views/Project/Index.cshtml
- Frontend/Views/Transfers/IncomingTrust.cshtml
Content changes
Minor Content Updates
> \Content changes

- Frontend.Tests/ControllerTests/Projects/TransferDatesControllerTests.cs
- Frontend.Tests/ValidatorTests/TransferDates/HtbDateValidatorTests.cs
- Frontend/Controllers/Projects/TransferDatesController.cs
- Frontend/Models/TransferDates/HtbDateViewModel.cs
- Frontend/Validators/TransferDates/HtbDateValidator.cs
- Frontend/Views/TransferDates/FirstDiscussed.cshtml
- Frontend/Views/TransferDates/HtbDate.cshtml
Update AB dates page validation
Create date validators
Move validation out of controller
> Update AB dates page validation

- Frontend.Tests/ControllerTests/Projects/TransferDatesControllerTests.cs
- Frontend.Tests/ValidatorTests/TransferDates/TargetDateValidatorTests.cs
- Frontend/Controllers/Projects/TransferDatesController.cs
- Frontend/Models/TransferDates/TargetDateViewModel.cs
- Frontend/Startup.cs
- Frontend/Validators/TransferDates/TargetDateValidator.cs
- Frontend/Views/TransferDates/FirstDiscussed.cshtml
- Frontend/Views/TransferDates/HtbDate.cshtml
- Frontend/Views/TransferDates/TargetDate.cshtml
Refactor target date validation
Create target date validator
Remove validation from controller
Fix some wave accessibility issues flagged on date pages
> Refactor target date validation

- Frontend.Tests/ControllerTests/Projects/BenefitsControllerTests.cs
- Frontend.Tests/ModelTests/BenefitsSummaryTests/IntendedBenefitsSummaryTests.cs
- Frontend/Controllers/Projects/BenefitsController.cs
- Frontend/Frontend.csproj
- Frontend/Models/Benefits/BenefitsSummaryViewModel.cs
- Frontend/Pages/Shared/_BenefitsSummary.cshtml
- Frontend/Pages/Shared/_FeaturesSummary.cshtml
- Frontend/Pages/TaskList/HtbDocument/Preview.cshtml
- Frontend/Pages/TaskList/HtbDocument/Preview.cshtml.cs
- Frontend/Views/Benefits/Index.cshtml
Tech Debt - Add Benefits Shared Summary
Shared view added to avoid duplication in CYA and Preview
> Tech Debt - Add Benefits Shared Summary

- Frontend/Pages/Shared/_RationaleSummary.cshtml
- Frontend/Pages/TaskList/KeyStage2Performance/KeyStage2Performance.cshtml
- Frontend/Pages/TaskList/KeyStage4Performance/KeyStage4Performance.cshtml
- Frontend/Pages/TaskList/KeyStage5Performance/KeyStage5Performance.cshtml
- Frontend/Views/GeneralInformation/Index.cshtml
- Frontend/Views/LatestOfstedJudgement/Index.cshtml
- Frontend/Views/PupilNumbers/Index.cshtml
- Frontend/Views/Rationale/Index.cshtml
- Frontend/Views/Shared/_Layout.cshtml
677-devs-to-review-each-sprint-please-dont-move
minor content updates
> 677 content updates

- Frontend.Tests/ControllerTests/Projects/LatestOfstedJudgementControllerTests.cs
- Frontend.Tests/HelpersTests/TagHelperTests/GdsKeyValueTagHelperTests.cs
- Frontend/Controllers/Projects/LatestOfstedJudgementController.cs
- Frontend/Helpers/TagHelpers/GdsKeyValueTagHelper.cs
- Frontend/Models/LatestOfstedJudgementViewModel.cs
- Frontend/Pages/Shared/_OfstedSummary.cshtml
- Frontend/Pages/TaskList/HtbDocument/Preview.cshtml
- Frontend/Pages/TaskList/HtbDocument/Preview.cshtml.cs
- Frontend/Views/LatestOfstedJudgement/Index.cshtml
Remove duplication of ofsted summary sections
Add partial
Add view model
Update controller
> Remove duplication of ofsted summary sections

- end-to-end-tests/cypress/integration/project-runthrough.spec.js
touch preview page in E2E test
Add preview page to journey
> touch preview page in E2E test

- Data.Mock/MockTrustsRepository.cs
- Data.TRAMS.Tests/TramsTrustsRepositoryTests.cs
- Data.TRAMS/TramsTrustsRepository.cs
- Data/ITrusts.cs
- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Views/Transfers/IncomingTrust.cshtml
- end-to-end-tests/cypress.json
- end-to-end-tests/cypress/integration/error-messages/target-date.js
- end-to-end-tests/cypress/integration/trust-transfers/search-incoming-trust.js
- end-to-end-tests/cypress/integration/trust-transfers/trust-transfer.spec.js
81385 remove outgoing trust from incoming trust search trusts
81385 remove outgoing trust from incoming trust search trusts
> 81385 remove outgoing trust from incoming trust search trusts

- Frontend.Tests/ValidatorTests/TransferDates/FutureDateValidatorTests.cs
- Frontend/Validators/TransferDates/FutureDateValidator.cs
- Frontend/Validators/TransferDates/HtbDateValidator.cs
> Update error message and don't validate if unknown date

- .github/workflows/end_to_end_tests.yml
> Add Record Key to Cypress test workflow

- Data.Mock/MockTrustsRepository.cs
- Frontend/Views/Shared/_Layout.cshtml
Add Give feedback section and feedback link to footer
Add Give feedback section and feedback link to footer
Update Mock Repository method
> Feature - Add Give feedback to footer

- Frontend/Views/Shared/_Layout.cshtml
Open feedback link in a new tab
Open feedback link in a new tab
> Open feedback link in a new tab

- Frontend.Tests/PagesTests/Projects/AcademyAndTrustInformation/IndexTests.cs
- Frontend/Pages/Projects/AcademyAndTrustInformation/Index.cshtml.cs
- Frontend/Pages/TaskList/HtbDocument/Preview.cshtml.cs
> Fix preview document

- Frontend.Tests/ControllerTests/Projects/BenefitsControllerTests.cs
- Frontend.Tests/PagesTests/PageTests.cs
- Frontend.Tests/PagesTests/Projects/AcademyAndTrustInformation/IndexTests.cs
- Frontend.Tests/PagesTests/Projects/AcademyAndTrustInformation/RecommendationTests.cs
- Frontend.Tests/PagesTests/Projects/Benefits/IndexTests.cs
- Frontend.Tests/PagesTests/TaskList/KeyStage2PerformanceTests.cs
- Frontend.Tests/PagesTests/TaskList/KeyStage4PerformanceTests.cs
- Frontend/Controllers/Projects/BenefitsController.cs
- Frontend/Pages/Projects/Benefits/Index.cshtml
- Frontend/Pages/Projects/Benefits/Index.cshtml.cs
- Frontend/Views/Benefits/IntendedBenefits.cshtml
- Frontend/Views/Benefits/OtherFactors.cshtml
- Frontend/Views/Project/Index.cshtml
Move Benefits View to Razor Page
Move Benefits View to Razor Page
> Move Benefits View to Razor Page

- Frontend.Tests/ControllerTests/Projects/RationaleControllerTests.cs
- Frontend.Tests/PagesTests/Projects/GeneralInformation/IndexTests.cs
- Frontend.Tests/PagesTests/Projects/Rationale/ProjectTests.cs
- Frontend/Controllers/Projects/RationaleController.cs
- Frontend/Frontend.csproj
- Frontend/Models/Rationale/RationaleProjectViewModel.cs
- Frontend/Pages/Projects/GeneralInformation/Index.cshtml
- Frontend/Pages/Projects/Rationale/Project.cshtml
- Frontend/Pages/Projects/Rationale/Project.cshtml.cs
- Frontend/Pages/Shared/_RationaleSummary.cshtml
Move rationale project view to razor page
Move view to razor page
Update existing controller
Update tests
Remove view
> Move rationale project view to razor page

- Frontend.Tests/HelpersTests/TagHelperTests/GdsCheckboxesTagHelperTests.cs
- Frontend.Tests/PagesTests/Projects/Benefits/IndexTests.cs
- Frontend/Helpers/TagHelpers/GdsCheckBoxesTagHelper.cs
- Frontend/Pages/Projects/Benefits/Index.cshtml.cs
> Tech Debt - Fix summary error link

- end-to-end-tests/cypress/integration/project-runthrough.spec.js
Fix rationale cypress tests
Fix rationale cypress tests
> Fix rationale cypress tests

- .github/workflows/end_to_end_tests.yml
Remove unused code
Remove unused code
> Remove unused e2e test code

- Frontend/Views/Transfers/OutgoingTrustDetails.cshtml
Fix if address line is null
Fix if address line is null on outgoing trust
> Fix if address line is null

- Frontend.Integration.Tests/BasicTests.cs
- Frontend.Integration.Tests/Views/Rationale/IndexIntegrationTests.cs
- Frontend.Tests/PagesTests/Home/LoginTests.cs
- Frontend.Tests/ValidatorTests/LoginValidatorTests.cs
- Frontend.Tests/ValidatorTests/RationaleProjectValidatorTests.cs
- Frontend/Controllers/HomeController.cs
- Frontend/Frontend.csproj
- Frontend/Models/LoginViewModel.cs
- Frontend/Pages/Home/Index.cshtml.cs
- Frontend/Pages/Home/Login.cshtml
- Frontend/Pages/Home/Login.cshtml.cs
- Frontend/Startup.cs
- Frontend/Validators/LoginValidator.cs
- Frontend/Views/Shared/_Layout.cshtml
- end-to-end-tests/cypress/integration/error-messages/advisory-board-date.js
- end-to-end-tests/cypress/integration/error-messages/target-date.js
- end-to-end-tests/cypress/integration/project-runthrough.spec.js
- end-to-end-tests/cypress/support/commands.js
Move Login to Razor Page
Move Login to Razor Page
> Techdebt/Move Login to Razor Page

- Frontend/Pages/Projects/Index.cshtml
- Frontend/Pages/Shared/_BenefitsSummary.cshtml
Update benefits and risks page
Update risks to be lowercase
Update change hidden text
> Update benefits and risks page

- Frontend.Tests/ValidatorTests/TransferDates/AdvisoryBoardDateValidatorTests.cs
- Frontend.Tests/ValidatorTests/TransferDates/TargetDateValidatorTests.cs
- Frontend/Validators/TransferDates/AdvisoryBoardDateValidator.cs
- Frontend/Validators/TransferDates/TargetDateValidator.cs
Fix bug with target and ab unknown dates
Selecting unknown on AB/Transfer date caused an exception due to the validator not checking if unknown was selected
> Fix bug with target and ab unknown dates

- Frontend/Pages/TaskList/KeyStage2Performance/KeyStage2Performance.cshtml
- Frontend/Pages/TaskList/KeyStage4Performance/KeyStage4Performance.cshtml
- Frontend/Pages/TaskList/KeyStage5Performance/KeyStage5Performance.cshtml
> Fix task-list links

- Frontend.Tests/ControllerTests/TransfersControllerTests.cs
- Frontend.Tests/ValidatorTests/Transfers/OutgoingTrustAcademiesValidatorTests.cs
- Frontend/Controllers/TransfersController.cs
- Frontend/Validators/Transfers/OutgoingTrustAcademiesValidator.cs
- Frontend/Views/Transfers/CheckYourAnswers.cshtml
- Frontend/Views/Transfers/IncomingTrust.cshtml
- Frontend/Views/Transfers/OutgoingTrustAcademies.cshtml
- end-to-end-tests/cypress/integration/error-messages/advisory-board-date.js
- end-to-end-tests/cypress/integration/error-messages/first-discussed-date.js
- end-to-end-tests/cypress/integration/error-messages/target-date.js
- end-to-end-tests/cypress/integration/multiple-academies/select-multiple-academies.js
- end-to-end-tests/cypress/integration/project-runthrough.spec.js
- end-to-end-tests/cypress/integration/trust-transfers/search-incoming-trust.js
Allow user to select more than one academy
84610
Update page headings
Remove hint text
Change radio buttons to checkboxes
Update code to support multiple academies being selected sent
Update incoming trust question
84612
Update check your answers page to ensure multiple academies are listed
> Add support for multiple transferring academies

- Data/Models/Academy.cs
- Frontend.Tests/ServicesTests/GetInformationForProjectTests.cs
- Frontend/Models/PreviewPageAcademyModel.cs
- Frontend/Pages/TaskList/HtbDocument/Preview.cshtml
- Frontend/Pages/TaskList/HtbDocument/Preview.cshtml.cs
- Frontend/Services/GetInformationForProject.cs
- Frontend/Services/Responses/GetInformationForProjectResponse.cs
Update preview page to support multiple academies
Display multiple academies in preview page where necessary
Update titles to match prototype
> 84618 update preview page

- Frontend.Tests/PagesTests/Projects/LatestOfstedJudgement/IndexTests.cs
- Frontend/Pages/Projects/LatestOfstedJudgement/Index.cshtml.cs
Fix back to preview for Ofsted
Fix back to preview for Ofsted
> Fix back to preview for Ofsted

- Frontend/Pages/TaskList/HtbDocument/Download.cshtml
- Frontend/Pages/TaskList/HtbDocument/Download.cshtml.cs
Fixes to generate project template page following content review
Remove hyphens where feasible from file name and download page
Change reference to AB template in download page to project template
> Content fixes

- end-to-end-tests/cypress/integration/project-runthrough.spec.js
I simply forgot to unskip the CREATE Academy Transfer test.
> UnSkip the Create Academy Transfer test

- end-to-end-tests/cypress/integration/project-runthrough.spec.js
Removed a pause command in one of the methods
> Removed a pause command in one of the methods

- end-to-end-tests/cypress/integration/End2EndTests/project-runthrough.spec.js
Mis-understood the exact steps involved with some of the back journeys.
Fixed it now.
> further backlink fixes

- end-to-end-tests/cypress/integration/End2EndTests/project-runthrough.spec.js
Forgot to Uncomment some code in E2E tests
> Uncomment code in E2E tests

- Data/Models/Projects/TransferBenefits.cs
- Frontend/Pages/Projects/Benefits/IntendedBenefits.cshtml
Change order and text of intended benefits
Changed order of intended benefits to match prototype
> Change order and text of intended benefits

- Data/Models/Projects/TransferBenefits.cs
Update ofsted option as per comment on ticket
On benefits page ensure ofsted option is capitalised
> Update ofsted option as per comment on ticket

- Data.TRAMS.Tests/Mappers/Request/InternalProjectToUpdateMapperTests.cs
- Data.TRAMS.Tests/Mappers/Response/TramsProjectMapperTests.cs
- Data.TRAMS/Mappers/Request/InternalProjectToUpdateMapper.cs
- Data.TRAMS/Mappers/Response/TramsProjectMapper.cs
- Data.TRAMS/Models/AcademyTransferProject/AcademyTransferProjectBenefits.cs
- Data.TRAMS/Models/AcademyTransferProject/AcademyTransferProjectFeatures.cs
- Data.TRAMS/Models/AcademyTransferProject/AcademyTransferProjectRationale.cs
- Data/Models/Projects/TransferBenefits.cs
- Data/Models/Projects/TransferFeatures.cs
- Data/Models/Projects/TransferRationale.cs
- Frontend.Integration.Tests/Fixtures/AcademiesApiFixtures.cs
88392 Add section complete - back end work to add fields
Add isCompleted fields to relevant sections
Add mapping and tests
> 88392 Add section complete - back end work to add fields

- Frontend/Pages/Projects/GeneralInformation/Index.cshtml
- Frontend/wwwroot/src/css/site.scss
Add acronyms for general information
Page updated with acronym
CSS updated
> Add acronyms for general information

- Frontend/Pages/TaskList/KeyStage2Performance/KeyStage2PerformanceTables.cshtml
- Frontend/Pages/TaskList/KeyStage4Performance/KeyStage4PerformanceTables.cshtml
- Frontend/Services/CreateProjectTemplate.cs
Update LA to be local authority
Update LA to be local authority
> Update LA to be local authority AB#89458

- Frontend/appsettings.json
Azure AD Sign in configuration
Move tenant id and client id out of secrets
> Move tenant id and client id out of secrets (not sensitive data) AB#93322

- .github/workflows/build_and_test.yml
- .github/workflows/build_test_deploy.yml
- Frontend.Integration.Tests/IntegrationTestingWebApplicationFactory.cs
- Frontend/appsettings.json
- terraform/main.tf
- terraform/variables.tf
Remove redundant secrets for AD Sign in
> Feature/93322 signin config remove redundant secrets AB#93322

- Frontend/Pages/Transfers/OutgoingTrustDetails.cshtml
- Swap "School name" for "Trust name"
> Swap "School name" for "Trust name" AB#92507

- Frontend/Pages/Projects/BenefitsAndRisks/IntendedBenefits.cshtml
- Frontend/Pages/Shared/_BenefitsSummary.cshtml
Typo for intended benefits
add ? to intended benefits
> add ? to intended benefits AB#87228

- Frontend/Pages/Projects/Index.cshtml
- Frontend/Pages/Projects/TransferDates/Index.cshtml
Update expected transfer dates to "Transfer dates"
> Update expected transfer dates AB#92846

- end-to-end-tests/cypress/integration/End2EndTests/project-runthrough.spec.js
- Projects do not contain KS 2 table so commenting out
> Task 100484: Comment out key stage 2 performance table

- Frontend.Tests/ValidatorTests/TransferDates/AdvisoryBoardDateValidatorTests.cs
- Frontend.Tests/ValidatorTests/TransferDates/DateValidatorTests.cs
- Frontend.Tests/ValidatorTests/TransferDates/TargetDateValidatorTests.cs
- Frontend/Pages/Home/Index.cshtml
- Frontend/Pages/Projects/Features/Index.cshtml
- Frontend/Pages/Projects/TransferDates/AdvisoryBoard.cshtml
- Frontend/Pages/Shared/_AcademyAndTrustSummary.cshtml
- Frontend/Pages/Shared/_TransferDatesSummary.cshtml
- Frontend/Properties/launchSettings.json
- Frontend/Startup.cs
- Frontend/Validators/TransferDates/AdvisoryBoardDateValidator.cs
- Frontend/Validators/TransferDates/TargetDateValidator.cs
> Content Changes

- Frontend/Pages/Shared/_AcademyAndTrustSummary.cshtml
- Frontend/Pages/TaskList/HtbDocument/Download.cshtml
> AT#100585 content changes

- Frontend/Pages/Home/Index.cshtml
- Frontend/wwwroot/src/css/site.scss
> Task 101327: (Transfers) Refactor the front-end of projects list page

- end-to-end-tests/cypress/integration/End2EndTests/project-runthrough-ks2.js
- end-to-end-tests/cypress/integration/End2EndTests/project-runthrough.spec.js
- Skipping tests as they are failing and need to be refactored
> Task 102975: Temporarily Skip tests

- Data.TRAMS/Mappers/Request/InternalProjectToUpdateMapper.cs
- Data.TRAMS/Mappers/Response/TramsProjectMapper.cs
- Data.TRAMS/Models/AcademyTransferProject/AcademyTransferProjectBenefits.cs
- Data/Models/Projects/TransferBenefits.cs
- Frontend.Integration.Tests/BaseIntegrationTests.MockData.cs
- Frontend.Integration.Tests/Fixtures/AcademiesApiFixtures.cs
- Frontend.Integration.Tests/IntegrationTestingWebApplicationFactory.cs
- Frontend.Integration.Tests/Pages/Projects/BenefitsAndRisks/EqualitiesImpactAssessmentIntegrationTests.cs
- Frontend.Integration.Tests/Pages/Projects/BenefitsAndRisks/IndexIntegrationTests.cs
- Frontend.Tests/Frontend.Tests.csproj
- Frontend.Tests/PagesTests/Projects/BenefitsAndRisks/ComplexLandTests.cs
- Frontend.Tests/PagesTests/Projects/BenefitsAndRisks/EqualitiesImpactAssessmentTests.cs
- Frontend.Tests/PagesTests/Projects/BenefitsAndRisks/FinanceAndDebtTests.cs
- Frontend.Tests/ValidatorTests/BenefitsAndRisks/EqualitiesImpactValidatorTests.cs
- Frontend/Models/Benefits/BenefitsSummaryViewModel.cs
- Frontend/Models/Benefits/EqualitiesImpactAssessmentViewModel.cs
- Frontend/Pages/Projects/BenefitsAndRisks/EqualitiesImpactAssessment.cshtml
- Frontend/Pages/Projects/BenefitsAndRisks/EqualitiesImpactAssessment.cshtml.cs
- Frontend/Pages/Projects/BenefitsAndRisks/Index.cshtml.cs
- Frontend/Pages/Shared/_BenefitsSummary.cshtml
- Frontend/Pages/TaskList/HtbDocument/Preview.cshtml.cs
- Frontend/Validators/BenefitsAndRisks/EqualitiesImpactValidator.cs
**Developer note: Required features of the task are fully implemented and completely functional. But unit tests still need to be introduced.**
- [Y] Rebased master
- [Y] Cleaned commit history
- [Y ] Tested by running locally
> Task 101970: Replicate equalities impact assessment design in transfers

- Frontend.Integration.Tests/Pages/Projects/BenefitsAndRisks/EqualitiesImpactAssessmentIntegrationTests.cs
- Frontend.Tests/ValidatorTests/BenefitsAndRisks/EqualitiesImpactValidatorTests.cs
- Frontend/Pages/Projects/BenefitsAndRisks/EqualitiesImpactAssessment.cshtml
- Frontend/Validators/BenefitsAndRisks/EqualitiesImpactValidator.cs
> AB#101970 equlities statement - updating validation as per feedback

- Data.TRAMS/Mappers/Response/TramsProjectMapper.cs
- Data.TRAMS/Models/TrustSummary.cs
- Data.TRAMS/TramsProjectsRepository.cs
- Data/Models/Projects/TransferringAcademies.cs
- Frontend.Tests/ServicesTests/ReferenceNumberServiceTests.cs
- Frontend/Services/ReferenceNumberService.cs
- Frontend/appsettings.json
The new project reference doesn't contain the region -
> AB#104155 region - have removed region from the project reference number

- Frontend/Pages/Projects/BenefitsAndRisks/EqualitiesImpactAssessment.cshtml
- end-to-end-tests/cypress/integration/benefits-and-risks/equalities-impact-assessment.js
> AB#104298 equalities - add cypress test

- end-to-end-tests/cypress/integration/benefits-and-risks/equalities-impact-assessment.js
> AB#104298 equalities - removing slash from path

- Frontend.Integration.Tests/Pages/ProjectType/ProjectTypeIntegrationTests.cs
- terraform/main.tf
> add missing " in terraform main.tf

- terraform/main.tf
removed superfluous misspelling in main.tf
> Fix terraform misspelling

- end-to-end-tests/cypress/integration/End2EndTests/project-runthrough.spec.js
- end-to-end-tests/cypress/integration/landing-page/landing-page.js
- end-to-end-tests/cypress/support/commands.js
Landing Page:
- Navigates to transfers via Landing page
- Navigates to back to landing page
> Task 106285: Landing Page Transfers Journey

- Frontend/Pages/ProjectType/Index.cshtml
Renamed an ID to match the expected value for an error link.
> Fix project type error ID.

- Frontend/Views/Shared/_AdditionalInformation.cshtml
> Updated Warning for ASP Data.

- Frontend/Pages/Home/Index.cshtml
> AB#108724 legal requirements - add test id

- .github/workflows/end_to_end_tests.yml
Removing folder path as it appears to be duplicated
> Fix: remove folder path

- .github/workflows/end_to_end_tests.yml
- renaming name and path of cypress-screenshot.
> Update yml cypress screenshots

- end-to-end-tests/cypress/support/commands.js
- locates project by name
- changes to change link tagging
> Fix: Commands for legal requirement

- .github/workflows/build_test_deploy.yml
- .github/workflows/tf-apply.yml
> AB#109333 tags - tag on release and merge to main

- Frontend/Pages/Home/Index.cshtml
- end-to-end-tests/cypress/e2e/project-filters/110767_project-title-filter.cy.js
- end-to-end-tests/cypress/support/commands.js
- end-to-end-tests/package-lock.json
- end-to-end-tests/package.json
This PR covers the functionally for Project Title filter in transfers. 
Covers the different scenario for Project Title filter in transfers
Atm the code is not running as I have made the changes in FE html files to use the cypress selectors. Once this merged the tests should also pass.
> Project Title filter functionality

- Frontend/Pages/Home/Index.cshtml
Adds a "no results" message and hides paging when no results are available.
> Display message for zero results and hide paging.

- Frontend/Pages/Home/Index.cshtml
Updated content on in empty state search result.
DevOps ticket: https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_sprints/taskboard/Prepare%20conversions%20and%20transfers/Academies-and-Free-Schools-SIP/Manage%20an%20academy%20transfer/Sprint%2040?workitem=112411
- Change the word "school" to "trust" in empty state search result
> AB#112411/Update content in empty state

- .github/workflows/build_test_deploy.yml
- .github/workflows/tf-apply.yml
- Frontend.Tests/ServicesTests/AzureAdTests/GraphClientFactoryTests.cs
- Frontend.Tests/ServicesTests/AzureAdTests/UserRepositoryTests.cs
- Frontend/Authorization/HeaderRequirementHandler.cs
- Frontend/Frontend.csproj
- Frontend/Models/User.cs
- Frontend/Pages/Users.cshtml
- Frontend/Pages/Users.cshtml.cs
- Frontend/Services/AzureAd/AzureAdOptions.cs
- Frontend/Services/AzureAd/GraphClientFactory.cs
- Frontend/Services/AzureAd/GraphUserService.cs
- Frontend/Services/AzureAd/UserRepository.cs
- Frontend/Services/Interfaces/IGraphClientFactory.cs
- Frontend/Services/Interfaces/IGraphUserService.cs
- Frontend/Services/Interfaces/IUserRepository.cs
- Frontend/Startup.cs
- Frontend/appsettings.json
- terraform/main.tf
- terraform/variables.tf
Load list of users from active directory. Have added rough page which allows me to test the changes with the new CI secrets on dev.
> AB#107729 assign project - get users from active directory

- end-to-end-tests/cypress/e2e/assign-transfer-project/112386_assign-project.cy.js
- end-to-end-tests/cypress/support/commands.js
This PR covers the test to assign the project to DO in Transfers.
Note: For one function `selectFirstProject` I have used css atm however need to add cypress selector. Which will be covered in another PR as I wanted to make sure first if all the tests are running fine.
> Assign project to DO

- Dockerfile
Fixes the .NET version in the Dockerfile.
> Dot net 6 update

- end-to-end-tests/cypress/e2e/legal-requirements/legal-requirements.cy.js
This PT covers more checks  for  Legal Refinements.
> Refine legal requirements for  transfers 

- Frontend/Pages/Projects/Features/Index.cshtml
- Frontend/Pages/Projects/Rationale/Index.cshtml
- Frontend/Pages/Shared/_FeaturesSummary.cshtml
> 109494 - fix typos

- Frontend/Pages/AccessibilityStatement.cshtml
Correct the email address on the accessibility statement page on Transfers
DevOps ticket: 
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_sprints/taskboard/Prepare%20conversions%20and%20transfers/Academies-and-Free-Schools-SIP/Manage%20an%20academy%20transfer/Sprint%2040?workitem=116312
- Correct the email address on the accessibility statement page on Transfers
> 16312 Correct the email address on the accessibility statement page

- .github/workflows/cip-build-deploy-development.yml
This change request adds a new Github Workflow which builds the custom Azure Dockerfile and pushes the resulting image to Azure Container Registry.
> Added build task for Azure CIP

- end-to-end-tests/cypress/e2e/benefits-and-risks/equalities-impact-assessment.cy.js
- end-to-end-tests/cypress/e2e/e2e-tests/project-runthrough.cy.js
- end-to-end-tests/cypress/e2e/error-messages/target-date.cy.js
This PR fixes the cypress tests for staging as the data varies between dev and staging . 
Now the tests will work in Dev as well as in Staging
Checked all the tests!
> Fix Cypress tests for staging

- Frontend/Services/AzureAd/GraphUserService.cs
This resolved the out of memory exception when retrieving users in prod for assigning a project.
> 116823 - fix paging requests when retrieving all users

- end-to-end-tests/cypress/e2e/Performance/preview and download template.cy.js
- end-to-end-tests/cypress/e2e/benefits-and-risks/equalities-impact-assessment.cy.js
- end-to-end-tests/cypress/e2e/e2e-tests/project-runthrough-ks2.cy.js
- end-to-end-tests/cypress/e2e/e2e-tests/project-runthrough.cy.js
- end-to-end-tests/cypress/e2e/error-messages/advisory-board-date.cy.js
- end-to-end-tests/cypress/e2e/landing-page/landing-page.cy.js
- end-to-end-tests/cypress/e2e/multiple-academies/select-multiple-academies.cy.js
- end-to-end-tests/cypress/e2e/trust-transfers/search-incoming-trust.cy.js
- end-to-end-tests/package-lock.json
- end-to-end-tests/package.json
Upgraded cypress version to 12.1.0 .
Fixed the tests.
Un-skipped test
> Upgrade Cypress version for Transfers

- .github/workflows/build_test_deploy.yml
- .github/workflows/tf-apply.yml
- Frontend/Models/Select.cs
- Frontend/Pages/ProjectType/Index.cshtml
- Frontend/Pages/ProjectType/Index.cshtml.cs
- Frontend/Pages/TaskList/HtbDocument/Download.cshtml
- Frontend/Program.cs
- terraform/main.tf
- terraform/variables.tf
New content added, URL to feedback form is a configuration item configured through the deploy process.
> Template Download Page "What happens next"

- Frontend/Pages/TaskList/HtbDocument/Download.cshtml
Small content changes to the download project template page.
> Content changes.

- .github/workflows/continuous-integration-terraform.yml
- .github/workflows/continuous-integration-tfsec.yml
Adds 2 workflows for running tests against the new terraform code used on Azure.
1) Scan terraform files using `tfsec` 
2) Ensure terraform files are valid, formatted and documented correclty using `terraform fmt`, `terraform validate` and `terraform-docs`
> Added CI tests for Terraform

- .github/workflows/build-and-push-image-development.yml
- Merge deployment step into previous job to ensure env is scoped correctly. Fixes issue of Azure container app being restarted with an invalid image tag causing it to never finish provisioning.
> Fix container image reference

- .github/workflows/build-and-push-image-development.yml
- Ensures the container image matches the release tag instead of the commit SHA
> Adjusted docker image tag to match release tag

- end-to-end-tests/cypress/.eslintrc.json
- end-to-end-tests/package-lock.json
- end-to-end-tests/package.json
This PR adds cypress esLint . Atm there is only 1 warning
Future plan is to add more esLint rules and fix the errors/warning
> Implement cypress esLint for transfers

- .husky/pre-commit
- end-to-end-tests/package-lock.json
- end-to-end-tests/package.json
- package-lock.json
- package.json
This PR covers the changes which has been done to make esLint check run before  any commit.
> Add git hook to run esLinst before commit

- README.md
- end-to-end-tests/package.json
Fix husky install issue at Npm install stage -https://github.com/DFE-Digital/prepare-academy-transfers/actions/runs/4113183744/jobs/7099005360
Also updating README file for eslint and Githook
> Fix npm husky install issue

- end-to-end-tests/package.json
Issue : https://github.com/DFE-Digital/prepare-academy-transfers/actions/runs/4114219010/jobs/7101301452
Looks like it could be a version issue thus updated the same.
> Another try to fix husky install issue

- .husky/pre-commit
- end-to-end-tests/package.json
- package-lock.json
- package.json
Reverting this as it's causing issues in github workflow for end-to-end-tests. On local it works fine. SO the suggestion is to make the changes for eslint and git hook in your local so that esLint run every time we commit
P.S: esLint anyway is running when we merge the PR even if we don't create git hook here explicitly.
These changes should allow `End-to-end-tests` workflow to run fine.
> Revert git hook changes

- terraform.gpaas-azure-migration/README.md
- terraform.gpaas-azure-migration/container-apps-hosting.tf
This PR includes a bug fix where Container Apps were not able to be restarted by GitHub workflows
> Updated Terraform module to v0.14.3

- .github/workflows/build-and-push-image.yml
This PR adds Cypress tests into the new Azure deployment workflow
> Add Cypress tests to deployment Github Action

- .github/workflows/build-and-push-image.yml
- Changed secret prefix from `CIP` to `AZURE` to add more context.
> Patch workflow secrets

- Dfe.PrepareTransfers.Data.TRAMS/TramsProjectsRepository.cs
- Dfe.PrepareTransfers.Data/AcademisationHttpClient.cs
- Dfe.PrepareTransfers.Data/IAcademisationHttpClient.cs
- Dfe.PrepareTransfers.Web/Startup.cs
> new http client added

- Dfe.PrepareTransfers.Web.Tests/ServicesTests/DocumentGeneratorTests.cs
- Dfe.PrepareTransfers.Web/Services/DocumentGenerators/RisksGenerator.cs
- Dfe.PrepareTransfers.Web/Services/GetProjectTemplateModel.cs
> 137599 generate project template for transfers fix

- Dfe.PrepareTransfers.Web/Pages/Home/Index.cshtml
- Dfe.PrepareTransfers.Web/Pages/Home/Index.cshtml.cs
This pull request will allow users to see how many pages exist. It will also hide middle pages as requested by the accessibility report
[Link to file](https://educationgovuk.sharepoint.com/:x:/r/sites/ServiceDeliveryDirectorate/_layouts/15/Doc.aspx?sourcedoc=%7B546C09CC-0C92-4430-9640-625AB56E6B1B%7D&file=DfE_Accessibility_Audit.xlsx&action=default&mobileredirect=true)
> pagination on home page

- Dfe.PrepareTransfers.Data/Models/AdvisoryBoardDecision/AdvisoryBoardDecision.cs
- Dfe.PrepareTransfers.Data/Models/AdvisoryBoardDecision/AdvisoryBoardDecisions.cs
- Dfe.PrepareTransfers.Data/Models/AdvisoryBoardDecision/AdvisoryBoardWithdrawnReason.cs
- Dfe.PrepareTransfers.Data/Models/AdvisoryBoardDecision/AdvisoryBoardWithdrawnReasonDetails.cs
- Dfe.PrepareTransfers.Web/ExtensionMethods/AdvisoryBoardExtensions.cs
- Dfe.PrepareTransfers.Web/Models/Links.cs
- Dfe.PrepareTransfers.Web/Pages/TaskList/Decision/DecisionDate.cshtml.cs
- Dfe.PrepareTransfers.Web/Pages/TaskList/Decision/RecordADecision.cshtml
- Dfe.PrepareTransfers.Web/Pages/TaskList/Decision/Summary.cshtml
- Dfe.PrepareTransfers.Web/Pages/TaskList/Decision/WhoDecided.cshtml.cs
- Dfe.PrepareTransfers.Web/Pages/TaskList/Decision/WhyWithdrawn.cshtml
- Dfe.PrepareTransfers.Web/Pages/TaskList/Decision/WhyWithdrawn.cshtml.cs
add withdrawn as an option for recording a decision
> Withdrawn status for transfers

- Dfe.PrepareTransfers.Web/Pages/TaskList/Decision/DecisionDate.cshtml
old value of 'Date conversion was @Model.DecisionText' made more generic with 'Date of decision'
> changed page title to read 'Date of decision'

- end-to-end-tests/package-lock.json
- end-to-end-tests/package.json
added cypress multi reporters to package.jason file
> added cypress multi reporters to package.jason file

- end-to-end-tests/cypress/e2e/e2e-tests/decisions/decisions_test.cy.ts
- end-to-end-tests/cypress/pages/newTransferProjectWithDecisions.ts
added deletion to the created decision project
> Decisions tests

- Dfe.PrepareTransfers.Web/Security/SecureHeadersDefinitions.cs
- Dfe.PrepareTransfers.Web/Startup.cs
- Remove duplicate header definitions
- Set Xss Protection to 0
- Moved forwardedHeader definition before response header manipulation
> Set HSTS using aspnet
